kubescape/kubescape

cautils/k8sinterface/k8sconfig.go
go.mod

Now it can get kubeconfig from `KUBECONFIG` env and `--kubeconfig` flag.

feat: support kubeconfig env

---

.github/workflows/build.yaml
cautils/customerloader.go
cmd/cluster.go
cmd/config.go
cmd/get.go
cmd/set.go

Add cluster config get/set. Fix build for windows in github workflow

Add  config clsuter & fix github workflow

---

README.md
opaprocessor/processorhandler.go
policyhandler/handlepullpolicies.go
policyhandler/k8sresources.go
scapepkg/exceptions/exceptionprocessor.go

Fixed #95 : Filtering namespaces based on name
Fixed #96 : Wildcard support for metadata only (and not for kubernetes labels) @slashben, Please review this feature.
Added like button to Readme.

Fixed #95, #96

---

README.md
cautils/reporterutils.go
cautils/scaninfo.go
clihandler/cliinterfaces/submit.go
clihandler/cmd/control.go
clihandler/cmd/framework.go
clihandler/cmd/rbac.go
clihandler/cmd/results.go
clihandler/cmd/root.go
clihandler/cmd/scan.go
clihandler/cmd/submit.go
clihandler/initcli.go
go.mod
go.sum
resultshandling/reporter/mockreporter.go
resultshandling/reporter/reporteventreceiver.go
resultshandling/results.go
smoke_testing/init.py
smoke_testing/smoke_utils.py
smoke_testing/test_command.py
smoke_testing/test_scan.py

* Adding yaml input support with control cmd
* Supporting submit command
* Adding E2E smoke test

Sbumit support

---

README.md
examples/exceptions/README.md
examples/exceptions/exclude-allowed-hostPath-control.json
examples/exceptions/exclude-deployments-in-ns-default.json
examples/exceptions/exclude-kube-namespaces.json
examples/exceptions/exclude-nginx-in-minikube.json
go.mod
go.sum

Adding basic exceptions documentation

---

cautils/scaninfo.go
clihandler/cmd/control.go
clihandler/cmd/framework.go
clihandler/initcli.go
examples/exceptions/README.md
smoke_testing/smoke_utils.py
smoke_testing/test_scan.py

fixed stdin support

---

resourcehandler/fieldselector.go
resourcehandler/fieldselector_test.go
resourcehandler/k8sresources.go

supporting list of include-namespaces

---

cautils/datastructures.go
clihandler/cmd/framework.go
opaprocessor/processorhandler.go
opaprocessor/processorhandler_test.go
opaprocessor/processorhandlerutils.go
policyhandler/handlenotification.go
resourcehandler/filesloader.go
resourcehandler/k8sresources.go
resourcehandler/resourceshandler.go
resultshandling/reporter/reporteventreceiver.go

We store the kubernetes objects in one structure and not more than that

store data only once

---

clihandler/initcli.go
examples/output_mocks/prometheus-verbose-flag.txt
examples/output_mocks/prometheus.txt
resultshandling/printer/junit.go
resultshandling/printer/prometheusprinter.go

@Joibel I reverted my changes (not all of them because we changed the base objects) and I update the mock results.

revert prometheus output

---

clihandler/cmd/download.go
opaprocessor/processorhandler.go

Hot fix - Download command

---

clihandler/initcli.go
clihandler/initcliutils.go
go.mod
go.sum
hostsensorutils/hostsensorgetfrompod.go
hostsensorutils/hostsensorinterface.go
hostsensorutils/hostsensormock.go
opaprocessor/processorhandler.go
opaprocessor/processorhandlerutils.go
resourcehandler/fieldselector.go
resourcehandler/fieldselector_test.go
resourcehandler/k8sresources.go
resourcehandler/k8sresourcesutils.go

* Update host sensor object
* Update cloudSupport object
* Getting cloud data 
* Testing cloud data

Update objects groping and kinds

---

go.mod
go.sum
opaprocessor/processorhandlerutils.go
opaprocessor/processorhandlerutils_test.go
policyhandler/handlenotification.go
resourcehandler/filesloader.go
resourcehandler/k8sresources.go
resultshandling/printer/prettyprinter.go
resultshandling/printer/printresults.go
resultshandling/printer/summary.go
resultshandling/printer/summeryhelpers.go
resultshandling/reporter/mockreporter.go
resultshandling/reporter/reporteventreceiver.go

* Adding controls URLs to results
* Update SaaS version URL
* Adding spinner when getting k8s resources and when submitting
* Support "skipped" when no resources where found
* Support host sensor and cloud describe resources display

CLI improvements 

---

README.md

Adding Kubescape katacoda playground

---

resultshandling/printer/v2/controlmapping/summeryhelpers.go

Like it says on the box: minor fix.

Fix typo in namespace

---

cautils/rbac.go

@dwertent , I needed to return this code, please talk to me

returning RBAC submit table

---

.gitignore
cautils/versioncheck.go
resultshandling/printer/v2/controlmapping/prettyprinter.go
resultshandling/results.go

* Fixed version display
* Resolved #349 
* Display scan score when saving to file

Minor fixes

---

resultshandling/printer/v1/junit.go

Added an additional if check to prevent the access of reports that are possibly nil

Fixes(#333) Added length check to prevent panic

---

.github/workflows/build.yaml
.github/workflows/build_dev.yaml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
Fixes #328, #342, #339

chore: sign container image with cosign

---

hostsensorutils/hostsensor.yaml

solve known K8s issue:
https://github.com/kubernetes/kubernetes/issues/92332

add explicit protocol TCP to host-sensor YAML

---

.github/workflows/build.yaml
README.md
build.py
cautils/customerloader.go
cautils/getter/armoapiutils.go
clihandler/clidownload.go
clihandler/clilist.go
clihandler/clisubmit.go
clihandler/cmd/rbac.go
clihandler/cmd/results.go

* Generate account ID only when uploading data
* Publish release sha256 #98

AccountID handling

---

build/Dockerfile

Closes #398 
Current  - 
With the change -

Fix release version in Dockerfile

---

build.py
cautils/getter/armoapi.go
cautils/getter/getpoliciesutils.go
cautils/getter/loadpolicy.go
cautils/logger/methods.go
cautils/scaninfo.go
clihandler/cmd/root.go

* Support staging 
* Fixed python build
* Cache handling

Updating cache handling

---

cautils/datastructuresmethods.go
cautils/versioncheck.go
cautils/versioncheck_test.go
clihandler/cmd/scan.go
go.mod
go.sum
opaprocessor/processorhandlerutils.go
opaprocessor/processorhandlerutils_test.go
registryadaptors/README.md

https://github.com/armosec/kubescape/issues/417#issuecomment-1060131195

Use semver.Compare for version check

---

core/cautils/fileutils.go
core/cautils/scaninfo.go
core/cautils/scaninfo_test.go
core/pkg/resourcehandler/k8sresourcesutils.go
core/pkg/resourcehandler/urlloader.go
go.mod
go.sum
httphandler/README.md
httphandler/go.mod
httphandler/go.sum
httphandler/handlerequests/v1/datastructure.go
httphandler/handlerequests/v1/datastructuremethods.go
httphandler/handlerequests/v1/datastructuremethods_test.go
httphandler/handlerequests/v1/prometheus.go
httphandler/handlerequests/v1/prometheus_test.go
httphandler/handlerequests/v1/requestshandler.go
httphandler/handlerequests/v1/requestshandlerutil_test.go
httphandler/handlerequests/v1/requestshandlerutils.go

Using [go-git-url](https://github.com/armosec/go-git-url) pks

Submit repo metadata in context

---

build/Dockerfile
httphandler/examples/microservice/ks-deployment.yaml
httphandler/examples/prometheus/ks-deployment.yaml
httphandler/handlerequests/v1/datastructuremethods.go
httphandler/handlerequests/v1/datastructuremethods_test.go

* Update build file
* Fixed API actionos

Update docker build

---

core/pkg/opaprocessor/processorhandler.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

cloud controls will show a command on how to fix them for the respective cloud provider

support fixCommand

---

cmd/scan/control.go
core/cautils/scaninfo.go
core/core/initutils.go
core/core/scan.go
core/pkg/policyhandler/handlenotification.go
core/pkg/policyhandler/handlepullpolicies.go
core/pkg/policyhandler/handlepullpoliciesutils.go
core/pkg/resultshandling/printer/v2/jsonprinter.go
core/pkg/resultshandling/printer/v2/utils.go
core/pkg/resultshandling/results.go
go.mod
go.sum
httphandler/README.md
httphandler/go.mod
httphandler/go.sum
httphandler/handlerequests/v1/datastructuremethods.go
httphandler/handlerequests/v1/datastructuremethods_test.go
httphandler/handlerequests/v1/requestshandler.go
httphandler/handlerequests/v1/requestshandlerutils.go
httphandler/listener/setup.go

* Adding `v1/status` api
* Update dependencies pkg
* Resolved [result files not being written](https://github.com/armosec/kubescape/issues/511)

REST api support 

---

core/cautils/customerloader.go
core/cautils/customerloader_test.go
core/cautils/getter/armoapi.go
core/cautils/getter/armoapiutils.go
core/core/download.go
core/core/list.go
core/core/scan.go
core/pkg/registryadaptors/armosec/v1/civarmoadaptor.go
core/pkg/registryadaptors/armosec/v1/civarmoadaptorutils.go
core/pkg/resourcehandler/k8sresources.go

* Fixed auth URL
* Adding unitests to customer loading

Image vuln data integration

---

README.md

This PR adds a message regarding maintenance to the README.

Add a maintenance message

---

core/cautils/workloadmappingutils.go
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/hostsensorutils/utils.go
core/pkg/resourcehandler/k8sresourcesutils.go

This pull request is dependent on [https://github.com/armosec/host-sensor/pull/1](https://github.com/armosec/host-sensor/pull/1)

New host sensor resources

---

core/cautils/helmchart.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go

* Fixed file separator 
* Update report size limit to 4mb

Fixed windows support, update limit size

---

core/pkg/resultshandling/reporter/v2/reporteventreceiver.go

align max report size with BE configuration

Decrease max report size

---

.github/ISSUE_TEMPLATE/feature_request.md

This PR adds an issue template for a Feature Request.

Add a feature request template

---

.github/ISSUE_TEMPLATE/bug_report.md

This PR adds a Bug Report issue template.

chore: Add a Bug Report issue template

---

README.md

Made changes in README file by adding discord link correctly

---

README.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1RmGetkr0ffzC6OmVDIm7pMJ55DsUdns%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=5r4c-hy)

Correction of grammatical errors

---

.github/PULL_REQUEST_TEMPLATE.md

Created a simple PR template for maintaining standards throughout the project

Added simple PR template

---

core/core/scan.go

As part of ARMO's contribution we are removing the ARMO company name from logs
None
None

Removing mention of ARMO in the initi log print

---

.github/PULL_REQUEST_TEMPLATE.md

I fixed a typo in the PULL REQUEST TEMPLATE file.

Fixed typo

---

README.md
docs/roadmap.md
httphandler/examples/prometheus/README.md

In this PR I fixed the broken links we had regarding Mac/Windows installations 
* Resolved #639
* Resolved #641 

Fixed links in readme

---

CONTRIBUTING.md
docs/proposals/container-image-vulnerability-adaptor.md

Edited a few words in CONTRIBUTING.md file. Its my first pull request so hope it works

Edited few words

---

docs/roadmap.md

Updated roadmap.md : Typo Error

---

httphandler/listener/setup.go

There was some **spelling mistakes** at multiple places, so I've made those changes to increase the better code readability

Fixed typo: for better code readability

---

README.md

Fixes #689
1> The icon was centre aligned giving it a better look and feel.
2> we have asked users to give a star to the repo .
Latest Improvement 

improved icon of kubescape in readme

---

CONTRIBUTING.md

- [ ✓] My code follows the style guidelines of this project

grammar error fixer in CONTRIBUTING.md

---

examples/exceptions/README.md

Fixed a few typos and grammatical mistakes in the readme.md

Fixed Typos in examples/exceptions/README.md

---

core/pkg/opaprocessor/processorhandler.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Adding fixed control input.
This allows the addition of non-configurable control inputs. Those inputs will be hardcoded in the controls

Adding fixed control input

---

README.md

docs : added gitpod badge in readme.md

---

.github/PULL_REQUEST_TEMPLATE.md

I correct some grammatical mistakes in the PULL_REQUEST_TEMPLATE.md file
Resolved #725 

grammatical mistake is corrected in PULL_REQUEST_TEMPLATE.md file

---

README.md

punctuation changes

---

docs/index.html

Found and fixed typo in the 'alt' attribute of img tag

fixed the typo in docs/index.html

---

.github/ISSUE_TEMPLATE/feature_request.md

"." at the end of the headings were missing and all the text were in same line.
Now this gives a clear and concise view of the texts.
- [x ] My code follows the style guidelines of this project

Fixed some typos in feature_request.md

---

build.py

removed command of comment from get_package_name(): function in build.py file
Resolved #758 

 build.py is modified

---

core/cautils/fileutils.go

Print chart name log when fail to generate

Print chart name log when fail to generate

---

docs/proposals/container-image-vulnerability-adaptor.md

fixed typos

---

docs/roadmap.md

Some grammatical mistakes in the roadmap.md are modified
#757 

 roadmap.md file is modified

---

build/Dockerfile

Updated Dockerfile with Alpine tag and optimized repeating commands.
#747

Updated Dockerfile

---

core/cautils/datastructures.go
core/core/scan.go
core/pkg/resourcesprioritization/prioritizationhandler.go
core/pkg/resourcesprioritization/prioritizationhandler_test.go
core/pkg/resultshandling/printer/v2/utils.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

- Added resources prioritization information 
- Result object contains the raw resource and the prioritization information

Resources Prioritization

---

README.md

Changes to README.md - publishing community meetings
* Resolved #

Publishing community meetings

---

core/pkg/registryadaptors/contribute.md

Fixed typos in contribute.md

---

httphandler/README.md

fixed some typo mistakes in the readme.md file
* Resolved #

 fixed some typo mistakes

---

docs/roadmap.md

Fixed typos in roadmap.md

---

core/pkg/resultshandling/printer/v2/htmlprinter.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/resourcetable.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

```
<testsuites errors="0" disabled="0" failures="1" tests="1" time="" name="Kubescape Scanning">
<testsuite name="" disabled="0" errors="0" failures="0" hostname="" id="0" skipped="" time="" timestamp="2022-09-13 10:48:55.347087027 +0000 UTC" file="example2/test.yaml">
<properties></properties>
<testcase classname="" status="" name="" time="">
<failure message="Total: 3 (Low: 1, Medium: 2, High: 0, Critical: 0)&#xA;&#xA;===================================================================================================================&#xA;&#xA;Resource: kind=Deployment/namespace=ns/name=test&#xA;&#xA;Test: Images from allowed registry&#xA;Severity: Medium&#xA;Remediation: You should enable all trusted repositories in the parameters of this control.&#xA;Link: …
```

Edit Junit output

---

core/pkg/resultshandling/printer/v2/junit.go

Print line separator in Junit format only if some controls failed

Print line separator only if some controls failed

---

cmd/download/download.go

it was confusing to understand the download command because there was an extra 'download' mentioned
* Resolved #809 

removed the extra 'download' word from the example

---

core/cautils/datastructures.go
core/cautils/getter/downloadreleasedpolicy.go
core/cautils/getter/getpolicies.go
core/cautils/getter/kscloudapi.go
core/cautils/getter/kscloudapiutils.go
core/cautils/scaninfo.go
core/core/initutils.go
core/core/scan.go
core/pkg/opaprocessor/processorhandler.go
core/pkg/resourcesprioritization/prioritizationhandler.go
core/pkg/resourcesprioritization/prioritizationhandler_test.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

1. This PR uncomments prioritization logic in Kubescape. 
2. As part of the new logic, raw resource will be sent in the Result object, along with its prioritization information.
3. "Attack Tracks"  take part in the resources priority calculation (more information about attack tracks can be found in https://github.com/kubescape/regolibrary/releases/tag/v1.0.195)

Prioritization

---

cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
core/cautils/scaninfo.go
core/pkg/opaprocessor/processorhandlerutils.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
go.mod
go.sum

This PR:
- Adds support for severity counters
- Adds support for CLI flags that set severity thresholds
- Terminates Kubescape with an exit code 1 if scan results exceed the severity thresholds
NOTE: No tests since we’re kinda in a rush.
* Resolved #

feat: fail on exceeding severity thresholds

---

cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
core/cautils/scaninfo.go
core/pkg/opaprocessor/processorhandlerutils.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Per 307 fail on severity counters

---

.gitignore

fixed typo in .gitignore file
* Resolved #

typo in .gitignore file

---

httphandler/README.md

* Resolved #
- [x ] My code follows the style guidelines of this project
- [ x] I have commented on my code, particularly in hard-to-understand areas
- [ x] I have performed a self-review of my code
- [ x] If it is a core feature, I have added thorough tests.
- [ x] New and existing unit tests pass locally with my changes

Fixed grammatical errors

---

README.md
core/cautils/fileutils.go
core/cautils/kustomizedirectory.go
core/pkg/resourcehandler/filesloader.go
go.mod
go.sum
httphandler/README.md
httphandler/go.mod
httphandler/go.sum

* Detecting if the given Directory is "Kustomize" Directory.
* Generating Kubernetes Resources(.yaml files) from the defined "kustomization.yml" file. 
* Converting them to Kubernetes Workloads for scanning using "Kubescape"
* Set the `SourceType` as Kustomize Directory 
* Set the `KustomizeDirectoryName`
#718 
Closes #718
)

Scan Kustomize Directory

---

core/pkg/registryadaptors/registryvulnerabilities/interfaces.go
core/pkg/score/score.go

Minor Code Refactoring
* Resolved #

Refactoring of Code Base

---

README.md

There is a punctuation mistake in readme file at  line number 386, i just corrected it
* Resolved #

Correcting Punctuation

---

docs/roadmap.md

This PR fixes few type errors, fixes all the linting errors present in the markdown file and modifies few of the content to make it more understandable and concise
* Resolved #

Fix typos, linting errors of markdown fil

---

.github/workflows/build.yaml

Issue #1424 https://github.com/sigstore/cosign/issues/1424
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>
As it was commented out and seen the latest development
It might be now working
* Resolved #

Cosign for quay.io in Github Action

---

.github/workflows/build-image.yaml
.github/workflows/build.yaml
.github/workflows/build_dev.yaml
.github/workflows/pr_checks.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml

Use workflow_call

---

core/pkg/hostsensorutils/hostsensorgetfrompod.go

Fixed host-sensor control plane info collecting

---

core/cautils/customerloader.go

Store default URLs in cache

---

core/cautils/scaninfo_test.go
core/pkg/resourcehandler/repositoryscanner_test.go
core/pkg/resourcehandler/urlloader_test.go

Commented out tests which made actual http calls.
I didn't remove the tests, just in case we decide to update the implementation with mocks
* Resolved #

commented out tests which made actual http calls

---

core/cautils/fileutils.go
go.mod

Updates to a newer version of gopkg.in/yaml

Upgrade to gopkg.in/yaml.v3

---

core/pkg/hostsensorutils/hostsensor.yaml

update hostsensor version
* Resolved #

update hostsensor version

---

README.md

Added tutorial on how to scan a container image registry.
* This PR provides a tutorial to an end user on how to scan a container image registry.

Added tutorial for scanning container image registry

---

core/core/initutils.go
core/pkg/resultshandling/reporter/v2/mockreporter.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

I added the `path` key to the exceptions object in armoapi-go and opa-utils

Add support to exceptions on repo (files) scan

---

core/cautils/getter/kscloudapi.go
core/cautils/helmchart_test.go
core/cautils/scaninfo.go
httphandler/handlerequests/v1/requestparser.go

https://pkg.go.dev/io/ioutil
Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
* Resolved #

remove deprecated ioutil package

---

cmd/list/list.go
core/cautils/getter/downloadreleasedpolicy.go
core/core/list.go

Fixed: Empty Lines before printing Controls and Added Invalid Format Error

---

core/cautils/controllink.go
core/cautils/getter/downloadreleasedpolicy.go
core/core/list.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
core/pkg/resultshandling/printer/v2/prometheusutils.go
core/pkg/resultshandling/printer/v2/resourcetable.go

pretty-print Controls format  made Pretty

---

.github/workflows/build.yaml
.github/workflows/build_dev.yaml
build.py
build/Dockerfile
httphandler/build.py

Updated Dockerfile and build script to support ARM images
> Building for ARM passed here: https://github.com/amirmalka/kubescape/actions/runs/3469551058/jobs/5796676181
> (Push failed due to credentials issue)

Fixed docker build to support ARM #919

---

core/cautils/scaninfo.go
core/core/download.go
core/core/initutils.go

Support loading exceptions from the cache, when failing to load from the GitHub repo.

PER-633 support loading exceptions from cache

---

cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
core/cautils/datastructures.go
core/cautils/scaninfo.go
core/core/scan.go
core/pkg/resultshandling/printer/v2/utils.go

- Present a new flag to omit raw resources when not needed. This change affects only when using the json output format v2.

Omit raw resources flag in json output

---

core/pkg/resultshandling/results.go

Handle Invalid Formats

---

core/pkg/resultshandling/printer/v2/junit.go

Fix JUnit format to Junit schema 
Add the source path to the JUnit file  when scanning a repository
* Resolved #

Fix Junit format

---

.github/workflows/build.yaml
.github/workflows/test.yaml

Change linux runner to 20.04 instead of ubuntu-latest
* Resolved #

change linux runner to 20.04 instead of ubuntu-latest

---

core/pkg/resultshandling/printer/v2/controltable.go
core/pkg/resultshandling/printer/v2/htmlprinter.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
core/pkg/resultshandling/printer/v2/resourcetable.go

On print and output related objects - adjusted to get controls only by id.

All prints and outputs to get data only by control ID

---

core/pkg/resultshandling/printer/v1/jsonprinter.go
core/pkg/resultshandling/printer/v1/prometheusprinter.go
core/pkg/resultshandling/printer/v2/controltable.go
core/pkg/resultshandling/printer/v2/htmlprinter.go
core/pkg/resultshandling/printer/v2/jsonprinter.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
core/pkg/resultshandling/printer/v2/printresults.go
core/pkg/resultshandling/printer/v2/prometheus.go
core/pkg/resultshandling/printer/v2/prometheusutils.go
core/pkg/resultshandling/printer/v2/reportingstructs.go
core/pkg/resultshandling/printer/v2/resourcetable.go
core/pkg/resultshandling/printer/v2/sarifprinter.go
core/pkg/resultshandling/printer/v2/sarifprinter_test.go
core/pkg/resultshandling/printer/v2/silentprinter.go
core/pkg/resultshandling/printer/v2/summaryhelpers.go
core/pkg/resultshandling/printer/v2/utils.go
core/pkg/resultshandling/reporter/v2/mockreporter.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
core/pkg/resultshandling/reporter/v2/reporteventreceiverutils_test.go
core/pkg/resultshandling/reporter/v2/utils.go
core/pkg/resultshandling/reporter/v2/utils_test.go

Renamed the package headings for the versioned package under:
* core/pkg/resultshandling/printer
* core/pkg/resultshandling/reporter
* Resolved #967
- [x ] I have performed a self-review of my code
- [x ] New and existing unit tests pass locally with my changes

chore(style): renamed versioned packages to stick to idiomatic conventions

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

opa-utils v0.0.216

---

core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go

update config scanning path

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

update opa-utils pkg with URL parsing fixed

---

core/cautils/scaninfo.go
core/core/download.go
core/core/initutils.go
core/core/scan.go
httphandler/handlerequests/v1/datastructuremethods.go

Code changed for bug 
* Resolved #1008 

bug fix for cannot read local artifacts

---

core/pkg/resultshandling/printer/v2/attacktracks.go

only attempt to print existing attack graphs

---

core/cautils/getter/loadpolicy.go
core/cautils/getter/loadpolicy_test.go
core/cautils/getter/testdata/controls-inputs.json

Signed-off-by: Frédéric BIDON <fredbi@yahoo.com>
Listing frameworks could return an empty element when a mix of different kinds of policy files are present.
I've added a unit test case, but no integration test.
Please refer to the test case provided with #1040 
* Resolved #1040

fix ListFrameworks (could return an empty element)

---

core/cautils/workloadmappingutils.go
core/pkg/hostsensorutils/hostsensor.yaml
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/hostsensorutils/utils.go
core/pkg/resourcehandler/k8sresourcesutils.go

Added support in hostscanner CNIInfo API

Support in CNIInfo

---

.github/workflows/00-test.yaml
.github/workflows/02-publish-artifacts.yaml
.krew.yaml
build.py
build/Dockerfile
cmd/completion/completion.go
cmd/config/config.go
cmd/delete/delete.go
cmd/delete/exceptions.go
cmd/download/download.go
cmd/fix/fix.go
cmd/list/list.go
cmd/root.go
cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
cmd/submit/rbac.go
cmd/submit/results.go
cmd/submit/submit.go
cmd/update/update.go
core/cautils/krewutils.go

add kubectl plugin with krew

---

core/cautils/display.go
core/core/scan.go
core/pkg/opaprocessor/processorhandler.go
core/pkg/opaprocessor/processorhandler_test.go
core/pkg/resultshandling/printer/v2/controltable.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Implemented a progress bar when running KS as a CLI tool. The progress bar starts when the execution gets to control processing and progresses upon completion of each control. This is an important usability improvement for users who scan big clusters and also helps the user to understand if there are outstanding controls that takes more time.
In the same PR I am adding a limitation of control names in the results table (pretty print). The current solution is that the whole control name is printed and it makes the table a mess.
Scan a relatively big cluster (to see the effect)

Progress bar in CLI

---

go.mod
go.sum

Signed-off-by: yiscah <yiscahls@armosec.io>

update k8s-interface - fix in get region

---

core/pkg/resourcehandler/k8sresources_test.go

Signed-off-by: yiscah <yiscahls@armosec.io>
added unit test
put an [x] in the box to get it checked 
-->

add unit test

---

build/Dockerfile

Signed-off-by: Matthias Bertschy <matthias.bertschy@gmail.com>

fix ksserver name in Dockerfile

---

.github/workflows/01-code-review-approved.yaml
.github/workflows/b-binary-build-and-e2e-tests.yaml
.github/workflows/c-create-release.yaml
.github/workflows/y-code-review-approved-gate-wf.yaml

Signed-off-by: Matan Shkalim <shekel8@gmail.com>

change wf trigger

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/01-code-review-approved.yaml
.github/workflows/02-release.yaml
.github/workflows/a-pr-scanner.yaml
.github/workflows/b-binary-build-and-e2e-tests.yaml
.github/workflows/c-create-release.yaml
build.py
build/Dockerfile
cmd/scan/scan.go
cmd/submit/results.go
core/cautils/scaninfo.go
core/core/initutils.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
core/pkg/resultshandling/results.go
httphandler/build.py

* Fixing Github actions so the tests will have an empty release string (@matanshk )
* Updating URL output to `compliance` (@yossi77 )
* Changed default JSON output to `v2`
* Removed `host-scanner` warning message
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<< WOW! Now you can see the scan results on the web >>
https://cloud.armosec.io/compliance/<cluster name>?utm_campaign=Submit&utm_medium=CLI&utm_source=GitHub
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Prepare for release

---

.krew.yaml
build.py

Several changes are needed before we can successfully submit our plugin to Krew.
- first, I forgot to change the filenames inside the `.krew.yaml` template
- second, it seems you need to include a LICENSE file inside the archive
- finally, we should explain why it is a good plugin idea https://github.com/kubernetes-sigs/krew-index/pull/2924#issuecomment-1420316485

Fixes for krew plugin submission

---

httphandler/go.mod
httphandler/handlerequests/v1/requestshandlerutils.go

Signed-off-by: David Wertenteil <dwertent@armosec.io>

Removed unwanted span

---

CONTRIBUTING.md

Added suggestion to use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in `CONTRIBUTING.md` guideline.
Closes #1093

docs(contributing): add semantic commit messages best practice

---

.krew.yaml

Signed-off-by: Matthias Bertschy <matthias.bertschy@gmail.com>

modify plugin description for krew approval

---

README.md

Correct the link to the release page as well as the release workflow.

fix(README): broken links

---

.github/workflows/02-release.yaml

Now that we have our krew plugin accepted, we can enable the action that will keep their index up-to-date with our releases.

enable krew plugin publishing action

---

core/pkg/resultshandling/printer/v2/html/report.gohtml
examples/output_mocks/html-format.html

Fixed HTML template.
Full output example can be found [here](
https://github.com/dwertent/kubescape/blob/fix-html-ouptput/examples/output_mocks/html-format.html
).
Screenshot:
* Resolved (at least the [HTML output issue](https://github.com/kubescape/kubescape/issues/1108#issuecomment-1437267993)) #1108

Fix HTML output

---

core/pkg/hostsensorutils/hostsensordeploy.go

This PR fixes the current `host-scanner` lifecycle behavior, improving namespace deletion only when needed.
Until now, **kubescape** was always deleting the namespace after the `host-scanner` finished its execution.
This is wrong, since the user could set a common namespace (default, kube-system, etc) by using the option `--host-sensor-yaml`. This causes the namespace deletion in the cluster that was not dedicated only for the `host-scanner`.
Now instead, **kubescape** checks if the user's provided namespace is already present on **kubernetes** and delete it after `host-scanner` execution, only if it was not present before.
To test this **PR**, I used the following samples in order to check the right behavior.
**[dedicated namespace]** (`hostsensor-with-dedicated-namespace.yaml`)
```yaml …
```

fix(hostsensorutils): improve namespace deletion in host-scanner lifecycle

---

core/pkg/opaprocessor/cosign_has_signature_test.go
core/pkg/opaprocessor/cosign_verify.go
core/pkg/opaprocessor/processorhandler.go
core/pkg/opaprocessor/processorhandlerutils.go

This PR reduces GC pressure during scans.
(draft): 
* this draft needs go.mod to be finalized (and also httphandler/go.mod)
* this draft include educational/testing profiling code to be removed
* requires https://github.com/armosec/armoapi-go/pull/44  to be merged and tagged
* requires https://github.com/kubescape/opa-utils/pull/74 to be merged and tagged
Signed-off-by: Frédéric BIDON <fredbi@yahoo.com>
* #1051 
cc: @matthyx @dwertent

fix(processorhandler): reduce GC pressure

---

httphandler/listener/setup.go

To reduce noise, separated monitored vs. non-monitored APIs.
Health check APIs will not be monitored - `/livez` & `/readyz`

Removed otel middleware from some APIs

---

core/core/initutils.go
core/pkg/resultshandling/reporter/v2/mockreporter.go
core/pkg/resultshandling/reporter/v2/mockreporter_test.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
core/pkg/resultshandling/reporter/v2/utils.go
docs/providers/armo.md

* Display URL only when account ID is set
* Update UTMs for creating account URL
* Display UTM only when a new account is created
This PR is instead of #1126

docs(links): Update URLs

---

core/pkg/hostsensorutils/hostsensor_mock_test.go
core/pkg/hostsensorutils/hostsensordeploy_test.go
core/pkg/hostsensorutils/hostsensorgetfromprod_test.go
core/pkg/hostsensorutils/kubernetes_mock_test.go

This PR adds unit tests to the hostsensorutils package.
Coverage is not perfect (74%), but good enough to cover the delicate business of the workerPool.
A limited mock is provided to emulate a kubernetes client with relatively simple test scenarios.

test(hostsensorutils): added unit tests to the hostsensorutils package

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

added CHECKOUT_REPO input parameter

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

added input to make the binary build and test dynamic

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

changed ks_branch to release

---

cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
core/cautils/display.go
core/cautils/display_test.go
core/core/scan.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
httphandler/handlerequests/v1/requestshandlerutils.go

* Update logs
* Update OTEL event
* Clear code
* Fix missing report ID

core(logs): Enhance logs

---

.github/actions/tag-action/action.yaml

Reverts kubescape/kubescape#1163

Revert "added validation for if ORIGIN_TAG=null"

---

core/pkg/hostsensorutils/hostsensordeploy.go
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/hostsensorutils/hostsensorgetfromprod_test.go

This PR factorizes the list of calls to the host-scanner API in a loop.
More godoc-friendly doc strings are added.

refact(hostsensorutils): refactors the host sensor

---

core/core/initutils.go
core/core/initutils_test.go
core/core/scan.go
core/pkg/hostsensorutils/hostsensordeploy.go
core/pkg/hostsensorutils/hostsensordeploy_test.go
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/hostsensorutils/hostsensormock.go
core/pkg/hostsensorutils/hostsensorworkerpool.go
core/pkg/hostsensorutils/json.go
core/pkg/hostsensorutils/utils.go
core/pkg/hostsensorutils/utils_test.go

This PR is scaffolded on top of #1141  and brings an extra level of refactoring.
The focus of this PR is to unexport private declarations that are not part of the interface exposed by this package.

refact(hostsensorutils): refactors host sensor exports

---

core/cautils/getter/kscloudapi.go

Updated `createTenant` API path

updated createTenant path

---

core/pkg/hostsensorutils/hostsensor.yaml

core(host-scanner): Update host scanner image tag

---

core/cautils/customerloader.go
core/cautils/customerloader_test.go
core/cautils/getter/kscloudapi.go

fix(config): Load account details

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/01-pr-merged.yaml

change trigger for wf

---

README.md

Changed Zoom URL and added timezone calculator.

Add new meeting location

---

cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
core/pkg/resultshandling/printer/v1/jsonprinter.go
core/pkg/resultshandling/printer/v1/prometheusprinter.go
core/pkg/resultshandling/printer/v2/controltable.go
core/pkg/resultshandling/printer/v2/jsonprinter.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
core/pkg/resultshandling/printer/v2/prometheus.go
core/pkg/resultshandling/printer/v2/prometheusutils.go
core/pkg/resultshandling/results.go
core/pkg/score/score.go
go.mod
go.sum
httphandler/examples/prometheus/README.md
httphandler/go.mod
httphandler/go.sum

adding compliance score updates

---

docs/getting-started.md

Broken link fixed on Getting-started-guide for Install on NixOS
Closes  #1191 
put an [x] in the box to get it checked 
- [ ✅ ] My code follows the style guidelines of this project
- [ ✅] I have commented on my code, particularly in hard-to-understand areas
- [✅ ] I have performed a self-review of my code
- [✅ ] If it is a core feature, I have added thorough tests.
- [ ✅] New and existing unit tests pass locally with my changes
Signed-off-by: Sindhuinti <iamsindhuinti23@gmail.com>

fix: broken link

---

core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go

fix(submit): set default report time

---

.github/actions/tag-action/action.yaml
cmd/fix/fix.go

* Fixed `fix` command example
* Fixed re-tag in workflows

fix(workflow): Fix workflow

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

Fix: https://github.com/kubescape/kubescape/pull/1148#issuecomment-1525813214

ci: update before install packages

---

.github/workflows/c-create-release.yaml
build.py
install.ps1

Resolve #1168 and mark `kubescape-windows-latest` as deprecated.

Add kubescape.exe to the release assets

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

add compliance score system test

---

.github/workflows/01-pr-merged.yaml
.github/workflows/a-pr-scanner.yaml
.github/workflows/b-binary-build-and-e2e-tests.yaml
build/Dockerfile
go.mod
httphandler/go.mod

Update go version from 1.19 to 1.20

Update go version 1.19->1.20

---

httphandler/handlerequests/v1/requestshandler.go

start with a new context, extracting span from request

---

core/pkg/hostsensorutils/hostsensordeploy.go

This PR fix the problem we have with `host-scanner` deletion.
With this fix we remove finalizers from `Namespace` which contains `host-scanner`, so it can be deleted faster.
This was the log we reported:
```
[error] failed to init host scanner. error: failed to apply host scanner YAML, reason: failed to create/update YAML, reason: failed to CREATE resource, workload: '{"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"labels":{"app":"host-scanner","k8s-app":"kubescape-host-scanner","otel":"enabled"},"name":"host-scanner","namespace":"kubescape-host-scanner"},"spec":{"selector":{"matchLabels":{"name":"host-scanner"}},"template":{"metadata":{"labels":{"name":"host-scanner"}},"spec":{"automountServiceAccountToken":false,"containers":[{"image":"quay.io/kubescape/host-scanner:v1.0.57","nam …
```

fix(hostsensorutils): add finalizers deletion

---

core/cautils/getter/testdata/policy.json
core/pkg/hostsensorutils/hostsensor.yaml
core/pkg/hostsensorutils/hostsensordeploy.go
core/pkg/hostsensorutils/hostsensordeploy_test.go
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/hostsensorutils/hostsensorworkerpool.go
core/pkg/hostsensorutils/log_coupling.go
core/pkg/hostsensorutils/log_coupling_test.go
core/pkg/hostsensorutils/logging_messages.go
core/pkg/resultshandling/reporter/v2/testdata/mock_opasessionobj.json

This adds some fix/improvements for `host-scanner` component.
This PR is the sum of other sub-PRs previously provided.
Due to possible conflicts, we moved them under a dedicated branch to test them all together.
* https://github.com/kubescape/kubescape/pull/1217
* https://github.com/kubescape/kubescape/pull/1224
* https://github.com/kubescape/kubescape/pull/1231
* https://github.com/kubescape/kubescape/pull/1202

host-scanner improvements

---

httphandler/handlerequests/v1/prometheus.go
httphandler/handlerequests/v1/prometheus_test.go

In this PR I changed some of the default configurations so the `v1/metrics` should response relatively fast.

core(metrics api): Update API default behavior

---

core/pkg/resultshandling/printer/v2/controltable.go
core/pkg/resultshandling/printer/v2/controltable_test.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/testdata/mock_summaryDetails.json
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Correcting the formatting of table in pdf output
Resolved: #1108
Update new table looks like this [report.pdf](https://github.com/kubescape/kubescape/files/11575456/report.pdf)

correcting the formating of the table in pdf output

---

core/pkg/resultshandling/printer/v2/html/report.gohtml
core/pkg/resultshandling/printer/v2/resourcetable.go
examples/output_mocks/html-format.html

English language fix on Kubescape output

---

core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
core/pkg/resultshandling/reporter/v2/reporteventreceiver_test.go
docs/providers/armo.md

Updating the post-submit message based on marketing requirements

Update submit message

---

httphandler/handlerequests/v1/datastructuremethods.go
httphandler/handlerequests/v1/datastructuremethods_test.go

allow adding a fw name when running all

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

bump opa-utils

---

core/cautils/fileutils.go
core/cautils/fileutils_test.go
core/pkg/resourcehandler/filesloader.go
core/pkg/resourcehandler/handlepullresources_test.go

https://cyberarmor-io.atlassian.net/browse/SUB-1097

Error handle for empty resource scan

---

docs/providers/armo.md
docs/providers/install.ps1
docs/providers/install.sh

_Naughty/Busy David didn't write a description here_

docs(providers): Update ARMO docs

---

smoke_testing/smoke_utils.py

add prints to smoketest

---

core/core/list.go
core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable.go
core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan.go
core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils.go
core/pkg/resultshandling/printer/v2/resourcetable.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Updating the version of our table dependency since this version supports unicode character based tables and making the appropriate additions.
As discussed with @craigbox out of all the possible alternatives available to us for this, this one is the simplest and most efficient so we decided to go with this approach.
`kubescape list controls`
Or any other kubescape command which renders a tabular output
Before:
After:
Resolved #1059

feat: add unicode table

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

This version has a fix for scanning Ingress resources

bump k8s-interface version

---

docs/providers/install.sh
install.sh

* Execute a cluster scan after installation
* Handle when a cluster is not available 
* Refactor script to use functions
* Beautify the output
cc @chmod-777-shauli

Beautify install.sh script logs

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

The latest k8s-interface version fixes a bug in the exceptions mechanism

bump version

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

Tests have been merged to master branch

Revert e2e test branch

---

core/pkg/resultshandling/printer/v2/prettyprinter/utils.go

This PR changes the vulnerability summary printer implementation so it will print up until 4 images.

Print up until 4 images in vulnerability summary

---

httphandler/handlerequests/v1/requestshandlerutils.go

fix setting context name in httphandler

---

README.md

add Openssf badge

---

.github/workflows/d-publish-image.yaml

Fixing [this](https://github.com/kubescape/kubescape/actions/runs/6446729028/workflow)

Adding check-secret to build image wf

---

README.md

Adding scorecard badge 

---

README.md

Fixing naming to comply with external check

Fix in the README for changelog name

---

core/pkg/opaprocessor/processorhandler.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

use ControlConfigInputs, deprecate ConfigInputs

---

docs/installation.md

Update documentation to add info about how to install a previous version using curl & install.sh

Update installation.md to add instructions to install a previous version

---

core/pkg/resultshandling/printer/v2/sarifprinter.go

Replace sarif format output so that the driver name will be 'Kubescape'

image scanning - replace driver name in sarif format 

---

core/core/initutils.go
core/pkg/resultshandling/printer/printresults.go
core/pkg/resultshandling/printer/v1/jsonprinter.go
core/pkg/resultshandling/printer/v2/htmlprinter.go
core/pkg/resultshandling/printer/v2/jsonprinter.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/prettyprinter.go
core/pkg/resultshandling/printer/v2/sarifprinter.go

https://github.com/kubescape/kubescape/issues/1394#event-10661286950
https://github.com/kubescape/kubescape/issues/1434

print result to stdout when format argument specified

---

core/cautils/customerloader.go
core/cautils/getter/kscloudapi.go
core/pkg/resultshandling/printer/v2/prettyprinter/reposcan.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Bump logger version

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Update maroto version to the last v1 stable version.

Update maroto version from 0.42.0 to 1.0.0

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

The tests will no longer pass because KS does not manage (create/update/delete) a configMap for the configurations.

Remove deprecated tests

---

ADOPTERS.md

Adding Cox Communications Adopters

---

go.mod
go.sum

Fixes: https://github.com/kubescape/kubescape/issues/1452

Update the tablewriter version to latest

---

core/pkg/resultshandling/gotree/gotree_mock.go
core/pkg/resultshandling/gotree/gotree_test.go

Tests
___
This PR introduces a comprehensive test suite for the `core/pkg/resultshandling/gotree` package. The main changes include:
- Creation of mock trees for testing purposes
- Addition of tests for the `TreePrint` function
- Addition of tests for the `printText` function
- Addition of tests for the `printItems` function
___
- `core/pkg/resultshandling/gotree/gotree_mock.go`: This file contains the creation of mock trees that are used in the test suite. Different types of trees are created to ensure comprehensive testing.
- `core/pkg/resultshandling/gotree/gotree_test.go`: This file contains the test suite for the `gotree` package. It includes tests for the `TreePrint`, `printText`, and `printItems` functions.
</details>

Adding Test Suite for core/pkg/resultshandling/gotree

---

core/cautils/controllink_test.go
core/cautils/display_test.go
core/cautils/fileutils_test.go
core/cautils/getter/getpoliciesutils_test.go
core/cautils/getter/utils_test.go

Added Test Suite for cautils

---

main.go

Enhancement
___
This PR introduces an interrupt signal handler in the main function of the application. The key changes include:
- A channel is created to capture interrupt signals.
- The `signal.Notify` function is used to relay incoming interrupt and SIGTERM signals to the newly created channel.
- A goroutine is launched to listen for any signals on the channel. On receiving a signal, it logs an exit message and terminates the program gracefully.
___
- `main.go`: Added an interrupt signal handler to capture and handle interrupt and SIGTERM signals, allowing for a graceful shutdown of the program.
</details>

Implementation of Interrupt Signal Handler

---

core/cautils/jsonutils_test.go
core/cautils/krewutils_test.go
core/cautils/kustomizedirectory.go
core/cautils/kustomizedirectory_test.go
core/cautils/workloadmappingutils_test.go

Tests
___
This PR primarily focuses on enhancing the test coverage for the 'core/cautils' module. It introduces unit tests for multiple utility functions and fixes a bug. The key changes are:
- Addition of unit tests for jsonutils, krewutils, workloadmappingutils.
- A bug fix in 'IsKustomizeDirectory' function where it was incorrectly returning the parent directory.
- Addition of tests for 'kustomizedirectory'.
- Refactoring of 'kustomizedirectory.go' to extract the logic of cleaning path directory into a separate function 'cleanPathDir' for better code readability and reusability.
___
- `core/cautils/jsonutils_test.go`: Added unit tests for the 'PrettyJson' function in the 'jsonutils' package.
- `core/cautils/krewutils_test.go`: Added unit tests for …

Adding Unit Tests and Bug Fix for core/cautils

---

cmd/completion/completion.go
cmd/completion/completion_test.go
cmd/config/set_test.go
cmd/download/download.go
cmd/download/download_test.go
cmd/fix/fix_test.go
cmd/list/list.go
cmd/list/list_test.go
core/core/download.go
core/core/list.go

Tests
___
- Added test suites for the following packages: completion, config, download, fix, list.
- Fixed potential crashes in the completion, download, and list subcommands when no argument was provided.
- Updated `DownloadSupportCommands` and 'ListSupportActions' functions to return sorted slices of strings.
___
- `cmd/completion/completion.go`: Added checks for empty arguments and invalid arguments in the Run function.
- `cmd/completion/completion_test.go`: Added new test cases for GetCompletionCmd function, testing for expected and unexpected outputs.
- `cmd/config/set_test.go`: Added new test cases for GetSetCmd function, testing for valid and invalid arguments.
- `cmd/download/download.go`: Added a check for empty arguments in the RunE function. …

Enhancement: Added Test Suite for cmd package and Fixed Potential Crashes

---

core/pkg/resultshandling/printer/printresults_test.go
core/pkg/resultshandling/results_test.go
httphandler/config/config_test.go
httphandler/config/credentials_test.go
internal/testutils/dir_test.go
pkg/imagescan/imagescan_test.go

Tests
___
This PR focuses on adding unit tests for multiple packages in the project. The main changes include:
- Addition of new tests for the 'printer' package in the 'core/pkg/resultshandling/printer' directory.
- New tests for the 'results' package in the 'core/pkg/resultshandling' directory.
- Addition of tests for the 'config' package in the 'httphandler/config' directory.
- New tests for the 'testutils' package in the 'internal/testutils' directory.
- Addition of tests for the 'imagescan' package in the 'pkg/imagescan' directory.
___
- `core/pkg/resultshandling/printer/printresults_test.go`: Added tests for the GetWriter function with both empty and non-empty file names.
- `core/pkg/resultshandling/results_test.go`: Added a new test for the …

Enhancement: Added Unit Tests for Multiple Packages

---

core/pkg/resultshandling/printer/v2/sarifprinter.go
core/pkg/resultshandling/printer/v2/sarifprinter_test.go
core/pkg/resultshandling/printer/v2/summaryhelpers_test.go

Enhancement
___
This PR focuses on enhancing the printer package in the following ways:
- Added numerous tests for the printer package to ensure its functionality.
- Refactored the `addFix` function for better readability and understanding.
- Refactored the `calculateMove` function to prevent potential out of bounds crash.
- Updated logging to use formatted strings for better readability.
___
- `core/pkg/resultshandling/printer/v2/sarifprinter.go`: Refactored the `addFix` function to improve readability and understanding. The function now creates a new replacement, a new artifact change, and adds the artifact change to the result's fixes in separate steps. Also, refactored the `calculateMove` function to prevent potential out of bounds crash and updated …

Enhancement of the printer package with additional tests and refactoring

---

core/core/list.go
core/core/list_test.go
go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Closes #1518 
Enhancement
___
This PR introduces natural sorting when listing policies. The changes include:
- Replacing the standard string sorting with natural sorting for policy listing in the `list.go` file.
- Adding a new function `naturalSortPolicies` that sorts the policies in a natural order.
- Updating the test file `list_test.go` to include tests for the new natural sorting function.
___
- `core/core/list.go`: Replaced standard string sorting with natural sorting in the `List` function. Added a new function `naturalSortPolicies` for natural sorting of policies.
- `core/core/list_test.go`: Added new test cases for the `naturalSortPolicies` function to ensure it works as expected with different inputs.
</details>

Implement Natural Sorting for Policy Listing

---

core/pkg/resultshandling/printer/v2/resourcetable.go
core/pkg/resultshandling/printer/v2/resourcetable_test.go

Tests
___
This PR introduces enhancements and a comprehensive test suite for the `resourcetable` file. The key changes are:
- Enhancements to the `generateResourceHeader` function for dynamic header length, efficient header creation, and clearer code structure.
- Enhancements to the `appendFailedPathsIfNotInPaths` function to create a set for efficient checking of existing paths and appending failed paths if they are not already present.
- Addition of a comprehensive test suite for the `resourcetable` file, covering various functions and scenarios.
___
- `core/pkg/resultshandling/printer/v2/resourcetable.go`: The `generateResourceHeader` function has been enhanced for dynamic header length, efficient header creation, and clearer code structure. The …

Enhancement and Test Suite for ResourceTable

---

core/cautils/strutils.go
core/cautils/strutils_test.go

Enhancement
___
This PR includes enhancements and additional testing for the string utilities in the `core/cautils` package. The main changes are:
- Refactoring of the `ConvertLabelsToString` and `ConvertStringToLabels` functions in `strutils.go` for better performance and readability.
- Addition of edge case testing for these functions in `strutils_test.go` to ensure they handle a variety of scenarios correctly.
___
- `core/cautils/strutils.go`: Refactored the `ConvertLabelsToString` function to use a `strings.Builder` for better performance. Simplified the `ConvertStringToLabels` function by removing unnecessary condition checks and using `strings.SplitN` to split the label string.
- `core/cautils/strutils_test.go`: Added new test functions …

Enhancement and Testing of String Utilities

---

core/pkg/resultshandling/printer/v2/prometheusutils_test.go

Tests
___
This PR introduces a comprehensive test suite for the Prometheus utilities in the `core/pkg/resultshandling/printer/v2` package. The tests cover the following functionalities:
- Compliance Score Metrics Labels and Prefix
- Control Compliance Score Metrics Labels and Prefix
- Framework Compliance Score Metrics Labels and Prefix
- Resources Metrics Labels and Prefix
- Conversion to Row in Metrics
- Metrics String Representation
___
- `core/pkg/resultshandling/printer/v2/prometheusutils_test.go`: The file is new and contains the entire test suite for the Prometheus utilities. It includes tests for various structs and their methods, such as `ComplianceScore`, `ControlComplianceScore`, `FrameworkComplianceScore`, and `Resources`. It also tests …

Added Test Suite for Prometheus Utilities

---

core/pkg/hostsensorutils/hostsensordeploy.go
core/pkg/hostsensorutils/hostsensordeploy_test.go
core/pkg/hostsensorutils/testdata/hostsensor.yaml
core/pkg/hostsensorutils/testdata/notAYamlFile.txt

enhancement, tests
___
This PR introduces enhancements to the YAML file validation process in the 'hostsensordeploy.go' file. It also includes the addition of new test cases in 'hostsensordeploy_test.go' to ensure the correct functioning of the updated validation process. The main changes include:
- Validation for empty YAML files.
- Validation for non-YAML files.
- Addition of test cases for the new validations.
- Update of test file paths in the test cases.
- Addition of new test data files.
___
- `core/pkg/hostsensorutils/hostsensordeploy.go`: Added validation for empty YAML files and non-YAML files in the 'loadHostSensorFromFile' function.
- `core/pkg/hostsensorutils/hostsensordeploy_test.go`: Updated the file paths in the test cases and added new …

Enhancement of YAML File Validation and Corresponding Test Cases

---

core/pkg/resultshandling/printer/v2/jsonprinter.go
core/pkg/resultshandling/printer/v2/jsonprinter_test.go
core/pkg/resultshandling/printer/v2/junit.go
core/pkg/resultshandling/printer/v2/junit_test.go
core/pkg/resultshandling/printer/v2/pdf.go
core/pkg/resultshandling/printer/v2/pdf_test.go
core/pkg/resultshandling/printer/v2/prometheus.go
core/pkg/resultshandling/printer/v2/prometheus_test.go

Enhancement
___
This PR introduces enhancements and test suites for the printer functions. The main changes include:
- Added handling for invalid scores in the `Score` function across multiple printer types (JsonPrinter, JunitPrinter, PdfPrinter, PrometheusPrinter). If the score is greater than 100, it is set to 100, and if it is less than 0, it is set to 0.
- Introduced test suites for the `Score` function in the corresponding test files for each printer type. The tests cover various scenarios including scores that are not integers, less than 0, greater than 100, and perfect scores.
___
- `core/pkg/resultshandling/printer/v2/jsonprinter.go`: Added handling for invalid scores in the `Score` function.
- …

Enhancement and Test Suite for Printer Functions

---

core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable_test.go
core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan.go
core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan_test.go

Tests, Refactoring
___
This PR includes enhancements and tests for the configuration printer. The changes are as follows:
- New tests have been added for the `categorytable` and `frameworkscan` components.
- The `shortFormatRow` function has been refactored for improved readability, consistency, modularity, and encapsulation.
- A new mock struct `MockISeverityCounters` has been added to test the `renderSeverityCountersSummary` function.
___
- `core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable_test.go`: New tests have been added for the `getCategoryTableWriter` and `renderSingleCategory` functions. These tests check the correct creation of tables and their rendering.
- …

Enhancements and Tests for Configuration Printer

---

core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/utils/utils_test.go
core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
core/pkg/resultshandling/printer/v2/prettyprinter/utils_test.go

enhancement, tests
___
This PR introduces performance enhancements and additional tests in the prettyprinter/utils.go file. The main changes include:
- Performance improvements in the `filterCVEsBySeverities` function by creating a map in advance to eliminate the need for repeated string comparisons.
- Performance improvements in the `getSortPackageScores` function by avoiding unnecessary map lookups.
- Performance improvements in the `getSortedCVEsBySeverity` function by avoiding map lookups, efficient sorting, and optimized output.
- Addition of tests for the `GetColor`, `ImageSeverityToInt`, `PrintInfo`, and `GetColorStatus` functions in the utils_test.go file.
___
- `core/pkg/resultshandling/printer/v2/prettyprinter/utils.go`: The file has been …

Performance Enhancements and Test Additions in prettyprinter/utils.go

---

core/core/initutils.go

Closes #1543 
Enhancement
___
This PR introduces enhanced logging mechanisms for when KS Cloud is used. The changes include:
- Logging a warning when the Kubescape Cloud API URL is not set and policies are loaded from cache.
- Logging a warning when there's a failure in listing frameworks.
___
- `core/core/initutils.go`: Added two logging warnings:
- When the Kubescape Cloud API URL is not set and policies are loaded from cache.
- When there's a failure in listing frameworks.
</details>

Enhancement of Logging Mechanisms for KS Cloud Usage

---

README.md

Adding slack badge to README.md

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/a-pr-scanner.yaml
.github/workflows/d-publish-image.yaml
build/Dockerfile
core/cautils/fileutils.go
core/cautils/fileutils_test.go
core/cautils/kustomizedirectory.go
core/cautils/kustomizedirectory_test.go
core/cautils/scaninfo.go
core/core/download.go
core/core/download_test.go
core/pkg/fixhandler/fixhandler_test.go
core/pkg/policyhandler/cache_test.go
core/pkg/resultshandling/printer/v2/prometheus_test.go
core/pkg/resultshandling/printer/v2/sarifprinter_test.go
internal/testutils/dir_test.go

fixed test

---

core/pkg/fixhandler/fixhandler_test.go

filepath test

---

core/pkg/fixhandler/fixhandler_test.go
core/pkg/resultshandling/printer/printresults_test.go
core/pkg/resultshandling/printer/v2/sarifprinter_test.go

Fixed filepath test

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/02-release.yaml
.github/workflows/b-binary-build-and-e2e-tests.yaml
.gitignore
.goreleaser.yaml

use goreleaser for builds

---

.github/workflows/00-pr-scanner.yaml

Added a check before running the binary-build job to ensure that the actor of the repository is kubescape, which makes only kubescape inner PR will be passed for username and password check.
* Resolved #1482

add github action actor check for pr-scanner

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/a-pr-scanner.yaml
.github/workflows/d-publish-image.yaml
README.md

Fixed link

---

core/pkg/resultshandling/printer/v2/sarifprinter.go

Remove repeating fixes

---

docs/roadmap.md

Updates to the roadmap as per decisions in the maintainers meeting

Updates in roadmap

---

core/pkg/containerscan/containerscan_mock.go
core/pkg/hostsensorutils/hostsensordeploy.go
core/pkg/hostsensorutils/hostsensorgetfrompod.go
core/pkg/resourcehandler/resourcehandlerutils.go

chore: fix function names in comment

---

cmd/rootutils.go
core/cautils/rbac.go
core/pkg/hostsensorutils/log_coupling.go
core/pkg/resultshandling/printer/v2/utils.go

Fix some comments

---

.github/workflows/00-pr-scanner.yaml
.github/workflows/02-release.yaml

Permissions

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

remove control_cluster tests

---

core/pkg/opaprocessor/processorhandlerutils.go
core/pkg/opaprocessor/processorhandlerutils_test.go

* Mask the environment variable values of initContainers and ephemeralContainers
* Expand unittests coverage

Mask all containers data

---

examples/exceptions/README.md

As controls are the "lowest" level for which we show results per resource it does not make sense to exclude running some rules in a control because the results would be unclear. 
Resolves #1655

update exceptions docs - ruleName not supported

---

.github/workflows/b-binary-build-and-e2e-tests.yaml

Use large runners for binary-build job

---

.github/workflows/04-publish-krew-plugin.yaml

chore: improve the publishing workflows for krew

---

core/pkg/resourcehandler/repositoryscanner.go
core/pkg/resourcehandler/repositoryscanner_test.go

Add a second condition in getFilesFromTree to ensure we are scanning the correct path

---

CONTRIBUTING.md
GOVERNANCE.md
MAINTAINERS.md
README.md

Update readme to use docs on kubescape.io; change some governance wording from heblish.
Signed-off-by: Craig Box <craig.box@gmail.com>

some easy doc fixes

---

.github/workflows/e-post-release.yaml

let's see if that helps: https://github.com/rajatjindal/krew-release-bot/issues/79

bump krew publish action

---

.github/workflows/02-release.yaml
.github/workflows/a-pr-scanner.yaml
go.mod
go.sum

Fixes kubescape/kubescape#1740

bump opa-utils version to fix apiVersion check 

---

core/core/initutils.go
core/pkg/resultshandling/results.go

fix some function name in comment
No need.

chore: fix some function name in comment

---

README.md

Changing Kubescape Readme to be incubating.

Changing README of Kubescape from Sandbox to Incubating

---

core/pkg/resultshandling/printer/v2/sarifprinter.go

fix helm detection in sarif printer

---

cmd/download/download.go
cmd/root.go
cmd/scan/control.go
cmd/scan/framework.go
cmd/scan/scan.go
cmd/scan/workload.go
cmd/update/update.go
cmd/version/version.go
cmd/version/version_test.go
core/meta/ksinterface.go

Added error handling and ensured context propagation across functions.

fix: add error handling and context propagation

---

cmd/root.go
cmd/rootutils.go
core/cautils/rootinfo.go

removing enable/disable colors, as not compatible with all loggers

---

go.mod
go.sum
httphandler/go.mod
httphandler/go.sum

Fix described in related PR:
* https://github.com/kubescape/opa-utils/pull/158

fix score calculation for framework with all controls in status irrelevant

---

.github/workflows/c-create-release.yaml
.goreleaser.yaml

generate checksums for all artifacts

---

httphandler/storage/apiserver.go

fixes https://github.com/kubescape/helm-charts/issues/652

check for nil map in merge methods

---

core/core/image_scan.go
core/core/patch.go
core/core/scan.go
pkg/imagescan/imagescan.go
pkg/imagescan/imagescan_test.go

close grype DB at the very end of processing
