- build/Dockerfile
Building the docker image does currently not work because go.mod does not exist.
By running: `docker build -t kubescape -f build/Dockerfile .`
It fails:
```
Step 7/10 : RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-s -w " -installsuffix cgo  -o kubescape .
---> Running in 3e7d4a124446
cautils/k8sinterface/cloudvendorregistrycreds.go:14:2: missing go.sum entry for module providing package github.com/aws/aws-sdk-go/aws (imported by github.com/armosec/kubescape/cautils/k8sinterface); to add:
go get github.com/armosec/kubescape/cautils/k8sinterface
cautils/k8sinterface/cloudvendorregistrycreds.go:15:2: missing go.sum entry for module providing package github.com/aws/aws-sdk-go/aws/session (imported by github.com/armosec/kubescape/cautils/k8sinterface); to add:
go get …
```
> fix: Fixed Docker build not working

- cautils/opapolicy/datastructuresmethods.go
responses that come from the same k8sresource (like containers from the same workload) - merged to one response
> remove redundant responses

- cautils/scaninfo.go
Closes #81.
setOutputFile() will incorrectly append .json to an --output
value that already has it. This is because
https://pkg.go.dev/path/filepath#Ext result includes
the ., whereas the current logic only tests against
json, not .json.
> Bugfix: correctly compare filepath.Ext() result

- README.md
Signed-off-by: Taylor Carpenter <taylor@vulk.coop>
Updating the link to the Kubernetes Hardening Guidance by NSA and CISA
Ref: https://github.com/armosec/kubescape/issues/97
> Fix link to hardening guide in README

- hostsensorutils/hostsensor.yaml
- hostsensorutils/hostsensordeploy.go
This could be useful to separate data from code.
In this way we have a dedicated `yaml` file to describe the `DaemonSet` which is going to be installed in the cluster.
> move kube-host-sensor manifest to indipendent yaml file with embed capability

- clihandler/cmd/control.go
- clihandler/cmd/framework.go
Closes #412 
kubescape fails with a proper error message if any of the framework/control is empty -
> Fix argument validation for framework/control

- cautils/scaninfo.go
- clihandler/cmd/scan.go
- clihandler/initcli.go
Our resources number is volatile. Thus, we would like to have a precise value in the fail-threshold test
> Change fail-threshold type to float

- cautils/logger/methods.go
- cautils/logger/prettylogger/colors.go
- cautils/logger/prettylogger/logger.go
- cautils/logger/zaplogger/logger.go
- cautils/scaninfo.go
- clihandler/cmd/root.go
Using commandline flag users can now disable colored output in logging.
Fixes: #434
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> cli: added support for no color

- core/pkg/resultshandling/printer/v2/controltable.go
- core/pkg/resultshandling/printer/v2/prettyprinter.go
This PR adds the **Severity** column to the Results table. 
The Severity column was present in the Web console but wasn't displayed in the Results table till now.
As per our conversation with @dwertent, instead of colouring the **Risk Score** column, we came up with the conclusion of colouring the **Severity** column.
**Screen shot**: 
Fixes https://github.com/armosec/kubescape/issues/320
Signed-off by: akundu@redhat.com
> Added Severity Column with colored text

- core/pkg/opaprocessor/processorhandlerutils.go
The current behaviour of kubescape is to list the control as "skipped" if it gets as input a host sensor resource (or any other armo resource) and the relevant flag was not used. 
This PR fixes it in a case where there are also k8s resources as input (so the control is not skipped). This behaviour is needed for control c-0079
> Check for empty k8s resources in controls related to armo resources 

- cmd/scan/scan.go
- core/cautils/getter/armoapiutils.go
- core/pkg/resultshandling/reporter/v1/reporteventreceiver.go
- core/pkg/resultshandling/reporter/v1/reporteventreceiverutils.go
- core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
- core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
- core/pkg/resultshandling/reporter/v2/utils.go
- core/pkg/resultshandling/reporter/v2/utils_test.go
- go.mod
- go.sum
The implementation of the cluster name parsing didn't include the case where the name, region, id etc was separated by ':'.
The code is here: https://github.com/armosec/k8s-interface/commit/8fd094f4d0acab4156896687194dc5def8380d4a
> Fix eks and support http for all endpoints

- cmd/scan/scan.go
- core/pkg/resultshandling/reporter/v1/reporteventreceiverutils.go
- core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
- core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
Useful for running with --env=http://localhost:7555. 
Up until now it was needed to switch all https to http
> support env with http

- cmd/scan/scan.go
- core/pkg/resultshandling/printer/printresults.go
- core/pkg/resultshandling/printer/v2/html/report.gohtml
- core/pkg/resultshandling/printer/v2/htmlprinter.go
- core/pkg/resultshandling/printer/v2/reportingstructs.go
- core/pkg/resultshandling/results.go
This PR would allow the Kubescape CLI users to output scan results to an HTML file.
The HTML report in a ZIP archive: [report.zip](https://github.com/armosec/kubescape/files/8899884/report.zip)
> feat: Print results to html

- core/cautils/fileutils.go
Remove an error if we try to read YAML file which is not a map[string]interface{}
> remove error when reading yaml

- core/pkg/resourcehandler/filesloader.go
Chart name map was accessed with the wrong key value (`source` is changed to `relSource`)
> helm chart name fix

- README.md
Since katacoda.com is closed and the scenarios were moved to killercoda, this PR updates the link in the Readme.
Closes #564
> Update link for playground in Readme 

- website/index.html
Their was a typo in index.html file.
Their was a small error as the title and h1 contains kubscape, and the name of our organisation is kubescape so, I've made that change to correct that typo
> typo: In the title and h1 element

- .github/workflows/close-typos-issues.yaml
* The workflow was intended to automatically comment & close any issues labelled "typo". Instead, it is throwing an error "PR run fail" and sending unnecessary emails for a PR due to a misconfiguartion.
* Corrected the above problem.
* Commenting automatically on issues labelled "typo" to open a PR with a relevant fix.
* Closing issues labelled typo automatically.
#754 
Closes #754
> Fixed: Misconfiguration in "close-typos-issues.yaml" GITHUB Actions file

- core/pkg/resourcehandler/filesloaderutils.go
- core/pkg/resourcehandler/remotegitutils.go
* Checked if the Git Repository is Public or Private.
* No Authentication is required for scanning Public Git Repositories
* Added authentication using GITHUB_TOKEN for scanning private Git repositories
#710
> Fixed: Kubescape fails to authenticate remote private Github repo

- cmd/scan/scan.go
- core/cautils/customerloader.go
- core/cautils/fileutils.go
- core/cautils/scaninfo.go
- core/pkg/containerscan/elasticdatastructures.go
- core/pkg/registryadaptors/armosec/v1/datastructures.go
- core/pkg/resultshandling/results.go
Fixed comment typos on multiple files, I have attached the file links under Screenshots.
**Typo 1 - Different is mistyped as "differnet":** https://github.com/kubescape/kubescape/blob/6e2dda799336bd857a7c68ee86f9815f4a3d5a42/core/cautils/scaninfo.go#L114
**Typo 2 - Support is mistyped as "supprot":**
https://github.com/kubescape/kubescape/blob/6e2dda799336bd857a7c68ee86f9815f4a3d5a42/core/cautils/customerloader.go#L181
**Typo 3 - Recursively and Directories are mistypes as "recuresively" & "directotries" respectively:**
https://github.com/kubescape/kubescape/blob/6e2dda799336bd857a7c68ee86f9815f4a3d5a42/core/cautils/fileutils.go#L33
https://github.com/kubescape/kubescape/blob/6e2dda799336bd857a7c68ee86f9815f4a3d5a42/core/cautils/fileutils.go#L265
**Typo 4 - Changed shitty to Bad as it can …
> Fixed typos on multiple files

- cmd/delete/exceptions.go
- cmd/download/download.go
- cmd/list/list.go
- cmd/scan/control.go
- cmd/scan/framework.go
- cmd/submit/exceptions.go
- cmd/submit/rbac.go
- cmd/submit/results.go
- core/cautils/rootinfo.go
- core/cautils/rootinfo_test.go
Signed-off-by: Anubhav Gupta <mail.anubhav06@gmail.com>
Fixes a Bad Request error when running a Kubescape scan with an Account ID that is not a valid UUID
This PR is in continuation to #577 
I've added the flag validation to all the commands (and their respective subcommands as well) which use the `--account` flag.
The commands which are covered are as follows:
1. `scan`
-> Subcommands: `framework`, `control`
2. `download`
3.  `delete`
-> Subcommands: `exceptions`
4. `list`
5. `submit`
-> Subcommands: `results`, `rbac`, `exceptions`
**Some** examples: 
* Resolved #605 
> add flag validation for --account-id (#605)

- cmd/scan/control.go
- cmd/scan/framework.go
- cmd/scan/scan.go
- cmd/scan/scan_test.go
- cmd/scan/validators_test.go
- core/cautils/scaninfo.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
Before this PR, severity threshold flags were separated by severity. This PR unifies these thresholds into one flag that forces Kubescape to terminate with an exit code 1 if there was at least one failed control at the specified severity threshold or above.
Requires kubescape/opa-utils#35
* Resolved #
> feat: unify severity threshold into one CLI flag

- README.md
* Clone the official GitHub repository of `Kubescape`.
* Install cmake.
* Install `libgit2` dependency inside 'kubescape' directory.
* Execute `make build` inside 'kubescape' directory.
* The entire process involves executing multiple commands in order and it takes around 5-6 minutes to execute them all.
* Apply changes you wish to make to the kubescape directory using text editors like `Vim`.
* Execute `make build` after the changes. (This will build the `kubescape` binary)
* Now, you can use Kubescape just like a normal user. Instead of using `kubescape`, use `./kubescape`. (Make sure you are inside kubescape directory because the command will execute the binary named `kubescape` in `kubescape directory`.
> Build on pre-configured killercoda's ubuntu playground (added documentation & Link to readme)

- README.md
- cmd/scan/scan.go
The code provides the `--kubeconfig` flag, used to use the kubeconfig file at that location.
As you can see in the code below, there's no need to write your own flag with **cobra**, because it is already coded by the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime#L39) package.
* Resolved #479
> feat: add `--kubeconfig` flag

- cmd/scan/scan.go
- core/cautils/customerloader.go
- core/pkg/resourcehandler/fieldselector.go
- core/pkg/resourcehandler/k8sresources.go
When running kubescape with `--include-namespace` or `--exclude-namespace` flags,
kubescape scan only Namespaced scop and not cluster scop, such as `cluster rule` etc.
* Resolved #608 
* Resolved #95 
> Scanning with include or exclude namespace, is only scan namespaced scope

- README.md
- cmd/scan/scan.go
- core/core/initutils.go
- httphandler/README.md
- httphandler/examples/microservice/README.md
Removing support for submitting results without accountID  
1. If account ID is empty, kubescape not create a new tenant 
2. If account ID is set, submit results (unless the --keep-local is set).
> Per 335 removing support for submitting results without accountid

- core/cautils/getter/loadpolicy.go
- core/pkg/policyhandler/handlepullpolicies.go
* Currently, the user will have no idea if Kubescape fails to read the file passed to the "controls-config" flag and it might be confusing if the user doesn't get the expected results from the scan.
* If the file passed to the "controls-config" flag cannot be opened or if there is any misconfiguration in the file, the user is notified of the error and the fact that the "controls-configs" are downloaded from the ARMO portal.
> Inform User if something is wrong with "controls-inputs" file they provided

- core/cautils/getter/loadpolicy.go
When kubescape takes the frameworks from a local file, it takes the data incorrectly.
And this causes the results when scanning with the `--use-artifact-from` flag, they different than when scanning normally.
The reason for this is that the object that holds the frameworks is shared by all the frameworks and if there are fields (like attributes) that are not in all the controls, they get the information from other controls
* Resolved #619 
> Fix reading frameworks from local file

- cmd/download/download.go
- core/cautils/getter/loadpolicy.go
- core/cautils/scaninfo.go
- core/core/download.go
- core/core/initutils.go
- core/pkg/resourcesprioritization/prioritizationhandler.go
Support loading attack tracks from the cache, when failing to load from the GitHub repo.
Support in `kubescape download attack-tracks` command
When using the `download artifacts` command, download also attack-tracks.
> Per 550 support loading attack tracks from cache kubescape

- core/pkg/resourcehandler/filesloader.go
Storing Absolute path Instead of Relative Path. The screenshots below are of `output.json` files form scan results. Observe `resources.Source.relativePath` field.
> Fixed: Wrong Relative Path When scanning Local Directory

- core/cautils/scaninfo.go
* Suppose the Git root repo is `orgname/kubernetes-manifests` and we are scanning from `orgname/kubernetes-manifests/deployments`, the `localRootPath` is being stored as `orgname/kubernetes-manifests/deployments` instead of `orgname/kubernetes-manifests`. 
* This creates inconsistencies when forming the paths of resource files from relative paths.
> Store Git Repo's root path as localRootPath

- core/pkg/resultshandling/printer/v2/html/report.gohtml
- core/pkg/resultshandling/printer/v2/htmlprinter.go
- core/pkg/resultshandling/printer/v2/reportingstructs.go
* For CIS control links old conventions are being passed when HTML output is generated. 
* Updated the link to new convention as decided in #904
> Fixed: CIS control link not working for html output format

- .github/workflows/build.yaml
- .github/workflows/test.yaml
Co-authored-by: Amir Malka <amirm@armosec.io>
Linux binary which is built on runner `ubuntu-latest` (22.04) was not working on ubuntu 20.04. GH updated runner version recently.
As a temporary WA - changed runner to previous version until issue is solved using latest runner version.
Ubuntu binary is now working both on ubuntu 22.04 and 20.04.
* Resolved #
> change linux runner to 20.04 instead of ubuntu-latest (#960)

- core/pkg/hostsensorutils/hostsensorworkerpool.go
Reverts kubescape/kubescape#973
> Revert "Excluding controlPlaneInfo from error message in case no data recieved."

- core/pkg/hostsensorutils/hostsensor.yaml
The value of allowPrivilegeEscalation followed implicit default of Kubernetes:
> AllowPrivilegeEscalation is true always when the container is:
> 1) run as Privileged
> 2) has CAP_SYS_ADMIN
For users still using PodSecurityPolicy (or a follow-up product like OPA Gatekeeper or Kyverno), there might be mutating admission controllers which defaults this field to `false` if unset. A value of `false` would then conflict with `privileged: true`.
`-`
`-`
> chore: Explicit set allowPrivilegeEscalation=true

- .github/workflows/build.yaml
- .github/workflows/test.yaml
- build/Dockerfile
- go.mod
- httphandler/go.mod
In this PR we are bumping the go version to `1.19`
> Bump go version to 1.19

- cmd/scan/scan.go
- core/cautils/datastructures.go
- core/cautils/scaninfo.go
- core/core/initutils.go
- core/core/initutils_test.go
- core/core/scan.go
- core/pkg/resourcesprioritization/prioritizationhandler.go
- core/pkg/resourcesprioritization/prioritizationhandler_test.go
- core/pkg/resultshandling/gotree/gotree.go
- core/pkg/resultshandling/printer/v2/attacktracks.go
- core/pkg/resultshandling/printer/v2/prettyprinter.go
- core/pkg/resultshandling/results.go
New argument `--print-attack-tree` will print prioritization information under the resources table.
By default, displayed top 15 resources and top 15 vectors. It is possible to override this behavior by the following env vars:
- `ATTACK_TREE_TOP_RESOURCES`
- `ATTACK_TREE_TOP_VECTORS`
Example: 
```
ATTACK_TREE_TOP_RESOURCES=100 kubescape scan --print-attack-tree
```
> Print attack tree (optional, with argument)

- core/cautils/localgitrepository.go
- core/cautils/localgitrepository_test.go
- core/pkg/containerscan/gojayunmarshaller.go
- core/pkg/containerscan/rawdatastrucutres.go
- core/pkg/resourcehandler/remotegitutils.go
This change fixes the case in which Kubescape would panic when scanning a local Git repository that:
- has the current branch that does not have an upstream set
- does not have an `origin` branch to fall back on
The panic happened because we did not check if the `origin` key exists in the map of upstreams. This change adds a test for this scenario and makes it pass by checking if the key exists. If it does not, it returns an error.
* Resolved #1005 
> Fix missing upstream panic

- core/cautils/localgitrepository.go
Fix a nil panic when calling scan from a git repository populated from `gh pr checkout 123`.
The `branch.remote` in a gitconfig file can be either a reference to a `remote` entry (what we check today) or directly a url:
```
[remote "origin"]
url = git@github.com:matthyx/kubescape.git
fetch = +refs/heads/*:refs/remotes/origin/*
[branch "dev"]
remote = origin
merge = refs/heads/dev
[branch "azure-scanning"]
remote = git@github.com:anubhav06/kubescape.git
pushRemote = git@github.com:anubhav06/kubescape.git
merge = refs/heads/azure-scanning
```
* Resolved #
> fix: branchRef.Remote can be a gitUrl

- core/cautils/scaninfo.go
- core/pkg/policyhandler/handlenotification.go
- core/pkg/policyhandler/handlenotification_test.go
Fix panic while scanning files/dirs.
```
kubescape scan test.yaml
go build -v -tags="static" .
github.com/kubescape/kubescape/v2/core/pkg/policyhandler
github.com/kubescape/kubescape/v2/core/core
[info] Kubescape scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33e61fe]
goroutine 1 [running]:
github.com/kubescape/kubescape/v2/core/pkg/policyhandler.setCloudMetadata(0xc0012b4000)
/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/core/pkg/policyhandler/handlenotification.go:91 …
```
> :bug: fix/panic

- core/pkg/policyhandler/handlenotification.go
Pushing the fix introduced in PR #1004
> setCloudMetadata only when scanning a cluster

- core/pkg/fixhandler/fixhandler.go
- core/pkg/resourcehandler/filesloader.go
```
./kubescape scan first.yml --format json --format-version v2 --output output.json
```
`Note: This is required when automatically creating pull requests using GitHub Actions`
> Add support for fixing Individual Files using "fix" command 

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- core/cautils/getter/loadpolicy.go
- core/cautils/getter/loadpolicy_test.go
- core/cautils/getter/testdata/controls-inputs.json
I mistakenly merged #1046 into `dev`, when we moved to targeting `master`. This change re-targets the misrouted commit, documents that we target `master` in new PRs and updates the Pull Request template accordingly.
Includes #1046.
Fixes #1040.
> chore: retarget a ListFrameworks fix, suggest targeting master in PRs

- install.sh
This PR fixes a bug in which the installation of Kubescape failed using the `install.sh` script.
Root cause: `bin` directory was missing in the `/usr/local/` path, as a result the script will not copy the Kubescape binary.
Fix: Create the full destination path for installation before copying the binary.
Bug found in MacOS Monterey
> fixed a bug in install.sh script

- cmd/scan/framework.go
- cmd/scan/scan.go
- core/cautils/getter/kscloudapiutils.go
- core/pkg/opaprocessor/cosign_has_signature.go
- core/pkg/opaprocessor/cosign_verify.go
- core/pkg/opaprocessor/utils.go
- core/pkg/policyhandler/handlepullpolicies.go
* Update the list of default frameworks to `AllControls`, `NSA`. `MITRE`
* Change cosign feature error logs from error level to debug level
In the current behavior, when running `lubescape scan`, Kubescape will fetch all of the available frameworks.
In this PR will are changing the behavior so Kubescape will fetch a specific list of chosen frameworks.
e.g.
Kubescape will scan the `AllControls`, `NSA`. `MITRE` frameworks when running
```
kubescape scan --logger debug
```
> Default frameworks

- cmd/scan/framework.go
- cmd/scan/scan.go
- core/cautils/getter/kscloudapiutils.go
- core/pkg/opaprocessor/cosign_has_signature.go
- core/pkg/opaprocessor/cosign_verify.go
- core/pkg/opaprocessor/utils.go
- core/pkg/policyhandler/handlepullpolicies.go
Signed-off-by: David Wertenteil <dwertent@armosec.io>
* Update the list of default frameworks to `AllControls`, `NSA`. `MITRE`
* Change cosign feature error logs from error level to debug level
In the current behavior, when running `lubescape scan`, Kubescape will fetch all of the available frameworks.
In this PR will are changing the behavior so Kubescape will fetch a specific list of chosen frameworks.
e.g.
Kubescape will scan the `AllControls`, `NSA`. `MITRE` frameworks when running
```
kubescape scan --logger debug
```
> Default frameworks (#1085)

- core/core/scan.go
- core/pkg/policyhandler/handlenotification.go
- core/pkg/policyhandler/handlenotification_test.go
- httphandler/go.mod
- httphandler/handlerequests/v1/requestshandlerutils.go
Signed-off-by: David Wertenteil <dwertent@armosec.io>
The ARMO Portal breaks down the cluster name to a more readable name:
Under the hood, Kubescape uses the context for splitting the name based on the cloud provider.
This does not work when running Kubescape as a microservice since the context is empty.
So it looks like the following:
We could not use the name for this because the name can be modified by the user.
In this PR, I added the option of loading a "context" from the environment variable. Because Kubescape is running as a microservice, this will have no effect on the running.
I will open an additional PR in the helm-chart with the environment variable.
/cc: @yossi77
> Loading kubeconfig name from env when running as a microservice  

- core/pkg/hostsensorutils/hostsensorgetfrompod.go
This PR fixes the error messages provided by kubescape when the host-scanner runs in a kubernetes managed by cloud providers.
In a managed kubernetes you don't have access to the control plan, so the `contrlPlaneInfo` endpoint was generating these errors.
Tests have to be done using a managed kubernetes. I used an instance of **EKS** on my side.
This was an example of the generated errors.
No issue were provided for this PR.
> fix: add check to skip controlplaneinfo in case of cloud providers

- core/pkg/hostsensorutils/hostsensorgetfrompod.go
Reverts kubescape/kubescape#1098
need to run it with another testcase.
> Revert "fix: add check to skip controlplaneinfo in case of cloud providers"

- build.py
Signed-off-by: Hollow Man <hollowman@opensuse.org>
I don't know if anyone had ever noticed, but the kubescape-xxxx-latest.tar.gz files in your release actually have the wrong LICENSE file.
https://github.com/kubescape/kubescape/releases/tag/v2.1.3
Correct the LICENSE file with the one that currently in the code base.
> fix(build): LICENSE file in release tarballs

- core/pkg/hostsensorutils/hostsensorgetfrompod.go
This **PR** fixes a weak check used to determine **kubescape** was scanning a cloud provider.
Now **kubescape** searches for cloud provider info, so, if at least one node has these kind of information, then we assumes that we are in a cloud provider environment (or at least in an hybrid one).
Tested on an **aws** environment and locally with **kind**, to have both the samples environments.
It is related to this other PR: #1098 
> fix(hostsensorutils): improve cloud provider detection

- .github/workflows/a-pr-scanner.yaml
- .github/workflows/b-binary-build-and-e2e-tests.yaml
Building Kubescape on macOS fails due to missing `pkg-config`.
Added `pkg-config` to the build process with brew; temporary, until issue below is resolved.
Root cause: https://github.com/actions/runner-images/pull/7125 (PR has been merged but macOS runner images were not published)
> Fix macos build - add missing pkg-config

- .github/workflows/02-release.yaml
- core/core/initutils.go
- core/core/initutils_test.go
- core/pkg/hostsensorutils/hostsensor.yaml
- core/pkg/resultshandling/printer/v2/htmlprinter.go
- core/pkg/resultshandling/printer/v2/jsonprinter.go
- core/pkg/resultshandling/printer/v2/junit.go
- core/pkg/resultshandling/printer/v2/pdf.go
- core/pkg/resultshandling/printer/v2/prettyprinter.go
- core/pkg/resultshandling/printer/v2/prometheus.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- core/pkg/resultshandling/printer/v2/silentprinter.go
- core/pkg/resultshandling/results.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
* Fixing krew release
* Removing OTEL from host scanner env. The host scanner will send telemetry when Kubescape runs as a microservice, and that env is set by the helm chart
> V2.2.1 patches

- core/pkg/hostsensorutils/hostsensor.yaml
This fix removes the `hostNetwork` and `hostPort` parameters from the `host-scanner` deployment, since we don't need them anymore.
Thanks to @matthyx for the suggested fix.
Run `kubescape scan --enable-host-scanner` to deploy the `host-scanner` on the cluster.
To test the parameters have been removed you can check for open port on the cluster: `nc -zv cluster.ip 7888`.
If you get no answer, then the parameters have been removed properly.
> fix(hostsensorsutils): remove hostNetwork and hostPort from deployment

- .github/workflows/00-pr-scanner.yaml
- .github/workflows/01-code-review-approved.yaml
- .github/workflows/02-release.yaml
- .github/workflows/03-post-release.yaml
- .github/workflows/a-pr-scanner.yaml
- .github/workflows/b-binary-build-and-e2e-tests.yaml
- .github/workflows/c-create-release.yaml
- .github/workflows/d-publish-image.yaml
- .github/workflows/z-close-typos-issues.yaml
This PR provides a simple security improvement in our CI workflows.
By pinning the workflows to a specific commit, we can ensure that the **github-action** we are using will not change during the time (if we don't update it).
This allows us to depend on a specific sha, still knowing what the original pinned version was.
Closes #1107 .
> ci: pin workflows versions to fixed commits

- core/pkg/hostsensorutils/hostsensor.yaml
I have updated the tolerations for node scanner Daemonset to make it runnable on all nodes of a cluster, regardless of present taints.
Current values:
- node-role.kubernetes.io/control-plane
- node-role.kubernetes.io/master
New value:
An empty key with the operator `Exists` matches all keys, values, and effects which means this will tolerate everything. 
[Reference](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
Kubernetes nodes may be tainted for different reasons or in some cases, tainted differently than what we expect, for instance, a cluster setup with RKE can have additional taints on its masters which prevents the node scanner to meet desired state.
Example of taints:
``` yaml
taints:
- effect: NoSchedule
key: node-role.kubernetes.io/controlplane …
```
> refactor: update node scanner daemonset tolerations

- httphandler/handlerequests/v1/prometheus.go
Initialize `scanRequestParams.ctx` with parent context to prevent panic when we reuse it to create otel spans.
* Resolved SUB-696
> initialize context in Prometheus handler

- .github/workflows/02-release.yaml
- .github/workflows/04-publish-krew-plugin.yaml
- .github/workflows/c-create-release.yaml
- .krew.yaml
- build.py
- install.ps1
There's an error that stops it from getting the right tag, which is, a `needs: retag` is needed so that it can get the value from `${{ needs.retag.outputs.NEW_TAG }}`:
However, fixing that won't work still: https://github.com/HollowMan6/kubescape/actions/runs/4392160217/jobs/7691893332
As you can't override the `GITHUB_REF` variable due to GitHub Actions' limit, quoting from the [GitHub Actions' documentation](https://docs.github.com/en/actions/learn-github-actions/variables#naming-conventions-for-environment-variables): "If you attempt to override the value of one of these default variables, the assignment is ignored." 
So I moved the Publish Krew plugin into a separate CI, which is triggered by exactly matching the tag created by the release CI. Also [as events triggered by the …
> ci(release): fix publishing krew plugin; add '.exe' extension to Windows binary

- core/cautils/workloadmappingutils.go
- core/pkg/resourcehandler/k8sresources.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
This integration uses the last feature introduced in `k8s-interface` repository that allows to retrieve information about `aws` policies.
Using this functionality, we can have more data available to make logic with rego rules.
This **PR** can be merged only after this other has been merged: https://github.com/kubescape/k8s-interface/pull/27.
After published the new `k8s-interface`, we have to update the `go.mod` file in `kubescape` in order to point it to the right version.
To test the given PR, you have to clone the `k8s-interface` repository locally:
```
git clone git@github.com:kubescape/k8s-interface.git && cd k8s-interface/
```
Check out to the feature branch:
```
git checkout feat/add-get-policy-version-method
```
add this line to the end of `go.mod` file:
```
replace …
```
> feat: integrate support to retrieve eks policies

- CONTRIBUTING.md
Fix the anchor link to signing off with the DCO.
> fix: wrong link in CONTRIBUTING.md

- go.mod
- go.sum
Upgrade opa-utils version to support exceptions using resourceID
Add exception with attributes designator with cluster and resourceID 
Scan and expect the resource to be ignored 
Exception example 
```json
{
"name": "exclude my resource by id",
"policyType": "postureExceptionPolicy",
"actions": [
"alertOnly"
],
"resources": [
{
"designatorType": "Attributes",
"attributes": {
"cluster": "cluster3",
"resourceID": "v1/core/default/ConfigMap/test"     
}
}
],
"posturePolicies": [
{
"frameworkName": "NSA",
"controlName": "Allowed hostPath"
}
]
}
```
https://github.com/kubescape/opa-utils/pull/101
https://github.com/armosec/armoapi-go/pull/74
- [x ] My code follows the style guidelines of this project
- [ x] I have commented on my code, particularly in hard-to-understand areas
- [ x] I have …
> upgrade opa-utils and armo-api

- httphandler/go.mod
- httphandler/go.sum
upgrade opa-utils in http handler (missed in http handler from PR https://github.com/kubescape/kubescape/pull/1149)
> add dependencies to httphandler

- cmd/completion/completion.go
Fixed help for completion; replaced references to `kubectl` with the executable name.
```sh
❯ kubescape completion
Error: accepts 1 arg(s), received 0
Usage:
kubescape completion [bash|zsh|fish|powershell]
Examples:
$ source <(kubescape completion bash)
$ echo 'source <(kubescape completion bash)' >> ~/.bashrc
$ source <(kubescape completion zsh)
$ echo 'source <(kubescape completion zsh)' >> "${fpath[1]}/_kubescape"
...
```
> fix references to kubectl in completion help

- core/cautils/getter/downloadreleasedpolicy_test.go
- core/cautils/getter/kscloudapi_mocks_test.go
- core/cautils/getter/loadpolicy_test.go
- core/pkg/fixhandler/fixhandler_test.go
- core/pkg/hostsensorutils/hostsensordeploy_test.go
- core/pkg/resultshandling/reporter/v2/mockreporter_test.go
- internal/testutils/dir.go
Introduced an internal package to start factorizing common test utilities.
The first such common function, "CurrentDir()", is used to retrieve test fixtures relative to a go source file, not necessarily the CWD.
> Refact(test utils): introduce internal/testutils

- install.sh
Resolve #1015 
The installation behavior now changes into the follows:
- If the user tries to start the script with root access, then kubescape will be installed into `/usr/local/bin/`.
- If without root access, then kubescape will be installed into `~/.kubescape/bin`, and a message will be shown to user asking them to put that directory into PATH manually.
> Change installation path to ~/.kubescape/bin

- core/core/scan.go
- core/pkg/opaprocessor/processorhandler.go
- core/pkg/policyhandler/handlenotification.go
- core/pkg/policyhandler/handlenotification_test.go
- core/pkg/resourcehandler/filesloader.go
- core/pkg/resourcehandler/k8sresources.go
- core/pkg/resourcehandler/resourceshandler.go
The PR add a progress bar during cloud resource download in order to return a feedback to the user, since this process can take a while.
As alternative, we can use the already existing spinner, but it doesn't not return a real feedback to the user.
Test it against an **EKS** cluster, since currently it is the provider where we retrive more information.
Here you add related issues and PRs.
* https://github.com/kubescape/kubescape/issues/1145
> feat: add progress bar during cloud resources download

- core/pkg/fixhandler/datastructures.go
- core/pkg/fixhandler/fixhandler.go
Fix the mixed up change list (I don't know why you use pointers here, which is actually the culprit):
https://github.com/kubescape/kubescape/blob/875deb7ec3ae05d838968cc410a5a6ac462f6632/core/pkg/fixhandler/fixhandler.go#L296-L305
`rulePaths` is a temporary variable, which will get released after use, it would of course be wrong if we store the address of that variable and try to use it after release.
```bash
kubescape scan test.yaml --format json --format-version v2 --output results
kubescape fix --no-confirm results.json
```
```yaml
apiVersion: v1
kind: Pod
metadata:
name: insert_to_mapping_node_1
spec:
containers:
- name: nginx_container
image: nginx
securityContext:
runAsNonRoot: true
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
securityContext:
runAsNonRoot: true …
```
> fix(fix): mixed up change summary list

- core/cautils/getter/downloadreleasedpolicy.go
The controls derived from `*DownloadReleasedPolicy.gs.getOPAControls()` do not have their `Frameworks` field filled. 
So, the alternative to get the `FrameworkNames` is by using `gs.GetOpaFrameworkListByControlID()`. Fixes one problem of #1176 .
`list controls` After Changes:
> Fix: Empty Frameworks Column when listing controls

- core/pkg/fixhandler/fixhandler.go
- core/pkg/fixhandler/fixhandler_test.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- core/pkg/resultshandling/printer/v2/sarifprinter_test.go
Add the [fix object](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317881) in Kubescape generated SARIF reports to reflect the available fixes generated by Kubescape.
The fix object represents a proposed fix for the problem indicated by the Result. It specifies a set of artifacts to modify. For each artifact, it specifies regions to remove, and provides new content to insert.
Although there maybe no instant benefit for this addition, hopefully there will be some in the future, as I have submitted a feature request at GitHub for supporting the fix object for their Code Scanning Tool: https://github.com/orgs/community/discussions/52156
```bash
kubescape test.yaml --format sarif
```
Example yaml file and generated sarif file packed in the zip file: …
> feat(sarif): add fix object in generated reports

- .github/workflows/a-pr-scanner.yaml
- .github/workflows/b-binary-build-and-e2e-tests.yaml
- .github/workflows/c-create-release.yaml
- .krew.yaml
- Makefile
- build.py
- install.sh
Resolve #195 #1112 
Add arm64 release binaries (both Linux and macOS) to release CI: kubescape-arm64-\<system>, as well as Krew.
macOS arm64 tests are not available in the CI.
Binaries to try out: https://github.com/HollowMan6/kubescape/releases/tag/v2.2.5
> arm64 release binaries for CI and Krew

- core/pkg/hostsensorutils/hostsensor.yaml
As described [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) the definition of probes, in out host-scanner manifest, is not correct.
This create issues when we try to apply the yaml file in this way:
```sh
kubectl apply -f https://raw.githubusercontent.com/kubescape/kubescape/master/core/pkg/hostsensorutils/hostsensor.yaml
Error from server (BadRequest): error when creating "https://raw.githubusercontent.com/kubescape/kubescape/master/core/pkg/hostsensorutils/hostsensor.yaml": DaemonSet in version "v1" cannot be handled as a DaemonSet: strict decoding error: unknown field "spec.template.spec.containers[0].readinessProbe.httpGet.initialDelaySeconds", unknown field …
```
> fix(hostsensorutils): fix indentation of probe attributes

- core/pkg/hostsensorutils/hostsensor.yaml
- core/pkg/hostsensorutils/hostsensordeploy_test.go
- core/pkg/hostsensorutils/hostsensorgetfrompod.go
Since we removed the `/kubeletconfigurations` endpoint from **host-scanner**, we need to remove it also from **kubescape**.
Here's the PR for **host-scanner**: https://github.com/kubescape/host-scanner/pull/41
Fix https://github.com/kubescape/kubescape/issues/1198
> fix: remove outdated enpoints

- core/pkg/resourcehandler/remotegitutils.go
In a call with a customer we saw with @yossi77 that the authentication failed with a private BitBucket repo.
After debugging it seems that BitBucket expects a special username `x-token-auth`.
TODO: in the future allow customers to specify a username ?
> change basic auth username to x-token-auth

- .github/workflows/03-post-release.yaml
Invoke packaging workflow to update after release.
Wait for:
- Transferring the [packaging repo](https://github.com/HollowMan6/packaging) under kubescape org: https://github.com/kubescape/kubescape/issues/1143#issuecomment-1497306913
- https://github.com/kubescape/homebrew-tap/pull/7 gets merged.
- https://github.com/kubescape/github-action/pull/38 gets merged.
Remember to add the **read and write** access to `Actions` for the GitHub Personal Access Token `secrets.GH_PERSONAL_ACCESS_TOKEN` with repo `kubescape/packaging` and `kubescape/homebrew-tap`.
> Invoke packaging workflow to update after release

- core/cautils/getter/utils.go
- core/cautils/getter/utils_test.go
Kubescape panics when the clientID and secretKey are set.
This happens when the response is empty, but no error was returned.
> fix(adaptors) Check response size

- install.ps1
Fix:
Test:
```bash
iwr -useb https://raw.githubusercontent.com/HollowMan6/kubescape/install/install.ps1 | iex
```
> Make powershell Windows installation user path available immediately

- .github/workflows/03-post-release.yaml
Fix workflow dispatch in release workflow.
- https://github.com/kubescape/kubescape/pull/1186#issuecomment-1530030415
By the way, please do make sure to add the read and write access to Actions for the GitHub Personal Access Token secrets.GH_PERSONAL_ACCESS_TOKEN with repo `kubescape/packaging`, `kubescape/github-action` and `kubescape/homebrew-tap` to ensure that this can work.
> Add ref to workflow dispatch

- .github/workflows/c-create-release.yaml
- build.py
As promised in https://github.com/kubescape/kubescape/pull/1169#issuecomment-1515931241 , You can choose to deprecate `kubescape-windows-latest` whenever you feel ready.
> Deprecate kubescape-windows-latest

- .github/workflows/c-create-release.yaml
- build.py
Reverts kubescape/kubescape#1213
We need to release Kubescape immediately, and I suspect this depreciation broke the smoke tests.
I'm reverting this for now, so we can fix it properly.
> Revert "Deprecate kubescape-windows-latest"

- CONTRIBUTING.md
The `CONTRIBUTING.md` file was lacking information on how to set up kubescape locally. To assist new contributors, I have added instructions for this purpose.
**Screenshots**
> Added instructions to setup kubescape locally

- core/cautils/reportv2tov1.go
- core/core/scan.go
- core/pkg/opaprocessor/processorhandler_test.go
- core/pkg/resourcesprioritization/prioritizationhandler.go
- core/pkg/resultshandling/printer/v2/junit.go
- core/pkg/resultshandling/printer/v2/prettyprinter.go
- core/pkg/resultshandling/printer/v2/summaryhelpers.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
Changes: 
- This PR bumps opa-utils version in order to support the new AllLists datastructure - mainly for memory optimizations.
Details on the above changes can be found in https://github.com/kubescape/opa-utils/pull/107
- Attack chains are now calculated only when flag is provided
-  https://github.com/kubescape/opa-utils/pull/107
> bump opa-utils version for memory optimizations

- core/cautils/getter/testdata/policy.json
- core/pkg/hostsensorutils/hostsensor.yaml
- core/pkg/hostsensorutils/hostsensordeploy_test.go
- core/pkg/resultshandling/reporter/v2/testdata/mock_opasessionobj.json
In this PR we are moving the previous dedicated **host-scanner**'s namespace (`kubescape-host-scanner`), to the current in use for **kubescape** operator (`kubescape`).
This is useful to avoid communication issues between namespaces when a policy engine is installed on the cluster.
Build **kubescape** by your own from this branch and run it against a cluster with the following command: `./kubescape scan --enable-host-scan`.
Check if **host-scanner** is deployed in `kubescape` namespace.
> fix: move host-scanner namespace

- core/pkg/hostsensorutils/hostsensor.yaml
In order to reduce the number of requests we should decrease the readiness probe periods.
This PR is related to [SUB-1286](https://cyberarmor-io.atlassian.net/browse/SUB-1286).
> fix(hostsensorutils): reduce periods of readiness probe

- core/pkg/hostsensorutils/hostsensordeploy.go
- core/pkg/hostsensorutils/hostsensorgetfrompod.go
- core/pkg/hostsensorutils/hostsensorworkerpool.go
- core/pkg/hostsensorutils/log_coupling.go
- core/pkg/hostsensorutils/log_coupling_test.go
- core/pkg/hostsensorutils/logging_messages.go
This PR add the possibility to couple logs coming from different nodes for the `host-scanner`.
To avoid logs duplication, we store them temporary in struct to keep track of them and check if they have already been used during the program execution.
To test this feature we need to force some kind of error/warning from the host-scanner.
To do so, I created an AKS cluster with 3 nodes (every kind of cluster is fine, but we need more than 1 nodes).
I updated the host-scanner version in the manifest to install it.
Here's the updated file:
```
apiVersion: v1
kind: Namespace
metadata:
labels:
app: kubescape-host-scanner
k8s-app: kubescape-host-scanner
kubernetes.io/metadata.name: kubescape-host-scanner
tier: kubescape-host-scanner-control-plane
name: kubescape-host-scanner
---
apiVersion: …
```
> feat: add log coupling for hostsensorutils

- core/pkg/hostsensorutils/hostsensor.yaml
- core/pkg/hostsensorutils/hostsensordeploy_test.go
- core/pkg/hostsensorutils/hostsensorgetfrompod.go
`/kubeletcommandline` has been replaced by `/kubeletinfo` endpoint.
Related issue: https://github.com/kubescape/host-scanner/pull/46
> fix: remove deprecated endpoint

- core/cautils/getter/testdata/MITRE.json
- core/cautils/getter/testdata/NSA.json
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
**Updating regolibrary (GitRegoStore) to version v1.0.286-rc.0:**
1. version includes a new file _security_frameworks_.
2. security_frameworks is expected to exist only from version v1.0.286-rc.0 and above for backward compatibility.
**New framework attribute "typeTags":**
1. a list of framework types, currently can be "compliance" and/or "security".
2. for compliance framework, typeTags is ["compliance"]
3. for security framework, typeTags is ["security"]
4. if no typeTags is configured or is empty, it will be considered as "compliance"
> Update regolibrary version

- core/cautils/customerloader.go
- core/cautils/customerloader_test.go
- core/pkg/hostsensorutils/hostsensordeploy.go
@alegrey91 at some point we would like to drop NS from our Helm chart, because anyways we're using the default one - this fix prepares for that
> initialize ns in case we don't have one in YAML

- cmd/scan/scan.go
- core/core/initutils.go
- core/core/scan.go
- core/pkg/resourcehandler/filesloader.go
- core/pkg/resourcehandler/k8sresources.go
- core/pkg/resourcehandler/registrydata.go
As part of the plan of separating between configuration scanning and image scanning, we are removing controls that are dependent on the image scanning results.
The first step is to deprecate the related flags and skip the adaptors when the credentials are not set. This way, new users will not set up the integration.
The full deprecation is introduced in #1263
> core(adaptors): Ignore adaptors when credentials are not set

- core/cautils/scaninfo.go
- core/core/initutils.go
Until now, kubescape will submit the results of cluster scanning and repo scanning.
Once this PR is released, Kubescape will submit also untracked files.
> feat(file scanning): Submit untracked files

- core/pkg/resourcehandler/filesloader.go
Occasionally due to certain conditions the spinner on the Kubescape cli binary would get stuck in place even after it would have been expected to disappear.
The cause for this is mainly the fact that once the spinner starts running if before it stops there is anything else that gets printed to the console like warnings or debug statements, that leads the spinner to skip a frame and re-render on the next line instead of the one it was already running on, leading to a print of the spinner to remain dormant then onwards and doesn't even gets cleaned.
So we stop the spinner just before anything is printed on the console and restart it after that.
```bash
kubescape scan resource.yaml
```
Before:
After:
Resolved #1280
> fix: stuck spinner

- core/pkg/fixhandler/yamlhandler.go
As mentioned in the issue, yaml nodes were being appended without checking for errors leading to redundant nodes being appended to the slice.
Not a user facing problem, but helps in ensuring variable safety in the code.
Run `kubescape fix output.json` for a previously generated `output.json` from `kubescape scan` and debug through the code.
Resolved #1290
> fix: yamlhandler error handling

- build.ps1
Currently for building from source on Windows environments we are dependent on `build.bat` and since `.bat` files are harder to handle/manage it is preferred to move to `.ps1` files instead which are the official Windows way of scripting.
The powershell script has been completely ported from `build.bat` and aims to replicate it's results and flow.
```powershell
build.ps1 all
build.ps1 install
build.ps1 build
```
Resolved #760 
Resolved #735
> feat: add build.ps1

- core/cautils/scaninfo.go
- core/pkg/fixhandler/fixhandler.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- smoke_testing/test_scan.py
When scanning a file/dir we change the scanning context so the data can be submitted similarly to repository scanning.
This caused the sarif handler and the fix command to panic in some cases.
In this PR I fixed the panic by saving the context of files/directories and a git.
> fix(results): Fixed results path

- core/pkg/resultshandling/printer/v2/controltable.go
As mentioned in the issue, the compliance score would be returned as `-1%` in case no resources were passed, it would be better to have this set to `N/A` which make more sense from a percentage and score point of view.
More context regarding the same can be found [here](https://github.com/kubescape/opa-utils/pull/117).
Create an empty `resource.yaml` then:
```bash
./kubescape scan resource.yaml
```
Before change:
After change:
Resolved #1282
> fix: negative compliance score

- cmd/download/download.go
- cmd/list/list.go
- cmd/scan/framework.go
- core/cautils/datastructures.go
- core/cautils/fileutils.go
- core/cautils/strutils.go
- core/cautils/workloadmappingutils.go
- core/core/initutils.go
- core/core/scan.go
- core/metrics/metrics.go
- core/pkg/opaprocessor/processorhandler.go
- core/pkg/opaprocessor/processorhandlerutils.go
- core/pkg/opaprocessor/utils.go
- core/pkg/resourcehandler/fieldselector.go
- core/pkg/resourcehandler/filesloader.go
- core/pkg/resourcehandler/handlepullresources_test.go
- core/pkg/resourcehandler/handlerpullresources.go
- core/pkg/resourcehandler/interface.go
- core/pkg/resourcehandler/k8sresources.go
- core/pkg/resourcehandler/k8sresourcesutils.go
- core/pkg/resourcehandler/k8sresourcesutils_test.go
- core/pkg/resourcehandler/queryableresource.go
- core/pkg/resourcehandler/registrydata.go
- core/pkg/resultshandling/reporter/v2/mockreporter_test.go
Follow up for comments made in PR #1300 
List of changes:
- Replaced `fmt.Sprintf` with `strings.Join`
- Replaced `cautils.StringInSlice` with `slices.Contains`
- Renamed `KSResources` to `ExternalResources`
- Defined constant strings for field selectors logic
- Use `ScanInfo` in `GetResources` function
> Code refactor (follow up to PR #1300)

- core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
Bug fix
___
This PR fixes the submit time in the `ReportEventReceiver` struct in the `reporteventreceiver.go` file.
___
- `core/pkg/resultshandling/reporter/v2/reporteventreceiver.go`: The `Submit` method in the `ReportEventReceiver` struct now updates the `reportTime` field with the current UTC time before submitting the report. This ensures that the submit time is accurate.
...
> Fix submit time

- core/pkg/opaprocessor/normalize_image_name.go
- core/pkg/opaprocessor/normalize_image_name_test.go
- core/pkg/opaprocessor/processorhandler.go
- core/pkg/opaprocessor/utils.go
- go.mod
This pull request introduces a new built-in function for Rego, designed to normalize container image names. Container image names come in various formats, which can lead to inconsistencies across different systems or services. This function aims to standardize the naming by applying a consistent set of rules and transformations. This normalization is essential for achieving uniformity and can be beneficial for integration with other tools, comparison, or simply for better alignment with an organization's naming conventions.
The normalization function introduced in this PR follows a set of well-defined rules, including:
* Lowercasing: All characters in the container image name are converted to lowercase to ensure uniformity.
Tag Handling: If a tag is not specified, a default tag (such as …
> Implementing container image name normalization built-in function for Rego

- core/core/list.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils.go
- core/pkg/resultshandling/printer/v2/resourcetable.go
*NOTE: DO NOT MERGE RIGHT NOW, INCLUDES SOME BREAKING CHANGES*
This PR aims to add the ability to color the table headers based off of the changes made in #1316. Hence that needs to be merged first before approaching this one, as a matter of fact, it'd be better to merge all the table related PRs first then move to this one.
The table library we are using supports colors internally using the `fatih/color` library which is the recommended method by them, I've used the `gchalk` library instead which leads to some table breaks here and there, but some of the other PRs if merged will be able to fix those issues.
Run any one of:
1) `kubescape list controls/frameworks/exceptions`
2) `kubescape scan resource.yaml`
> Color headers

- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/clusterscan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/reposcan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/summarytable.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils_test.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/utils/utils.go
- core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
- go.mod
As mentioned in the issue, we had moved to using the `gchalk` library for all our console output color needs, still some direct remnants of `fatih/color` remained because of which the output colors weren't consistent due to conflict between libraries. This PR removes all direct usage of `fatih/color` from the repo.
This only removes all direct dependence, some indirect independence still remains, mainly due to the `table` library we use which is built on top of `fatih/color` for it's coloring needs, though it is possible to find a workaround to remove this as well, but that should be on a need to do basis, as currently there is no problem since all direct usage has been removed.
`kubescape scan resource.yaml`
Resolved #1339
> feat: migrate fatih/color to gchalk

- cmd/scan/workload.go
- core/pkg/resourcehandler/filesloaderutils.go
- core/pkg/resourcehandler/k8sresources.go
Kubescape was panicking when scanning a workload which has an owner reference. This PR fixes that by checking for this error and validating list length
This PR also fix the workload scan logs, making them more readable by using the readable ID, and not printing the entire help message if we encounter an error during the scan.
> fix panic and improve logs

- core/pkg/resultshandling/printer/v2/prettyprinter/imagescan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils.go
- core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
- core/pkg/resultshandling/printer/v2/prettyprinter/utils_test.go
This PR improves the `scan image` command by:
1. Making colors of  "Negligible" and "Unknown" vulnerabilities similar to the ones in ARMO platform (before they were mostly not visible)
2. If no "High" and "Critical" vulnerabilities were found, the table will show "Medium" severity vulnerabilities (as opposed to not showing the table at all)
> improve cli output

- core/pkg/opaprocessor/processorhandler.go
- core/pkg/opaprocessor/processorhandler_test.go
Add additional support for related objects - resources that are related to the reason that another resource failed for a certain control. For e.g - a secret that is mounted to a deployment, causing the deployment to fail on a control that checks for mounted secrets. 
This PR adds support for showing assisted remediation (fix path, fail path, fix command) connected to a related resource that is not the main resource that's failing
> support paths from related resources

- core/core/scan.go
- core/pkg/resultshandling/printer/v2/htmlprinter.go
- core/pkg/resultshandling/printer/v2/jsonprinter.go
- core/pkg/resultshandling/printer/v2/junit.go
- core/pkg/resultshandling/printer/v2/pdf.go
- core/pkg/resultshandling/printer/v2/prometheus.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- core/pkg/resultshandling/printer/v2/utils.go
- core/pkg/resultshandling/results.go
- core/pkg/resultshandling/results_test.go
This PR fixes Kubescape panicking for image scanning when using output formats other than pretty printer and JSON (which are the only ones supported).
Previous behavior:
`kubescape scan image nginx --format junit`
Behavior with this PR:
`kubescape scan image nginx --format junit`
> fix panic & provide msg

- cmd/root.go
- cmd/scan/scan.go
- core/cautils/rootinfo.go
- core/cautils/scaninfo.go
- httphandler/handlerequests/v1/requestshandlerutils.go
Fix `--kube-context` flag by making it available to the root command, and move all initialization logic to `PreRun`
fixes #1365
> move context flag to root

- cmd/scan/framework.go
- cmd/scan/scan.go
- cmd/scan/validators_test.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
When running `kubescape scan` against any files, kubescape was skipping all the initialization logic (for example, initializing the correct logger).
Root cause: The  `scan ` command was calling the `framework` command inside the `Args` function, which is supposed to do only arguments validation. This caused the entire logic of  the `PersistentPreRun` function inside the `root` command, which perform the initialization, not to be called, since `Args` is called before (it was indeed called but only after the entire scan was performed).
This PR fixes this issue by moving this logic to the right place - inside the actual `RunE` function. It also adds a validation for the `framework` and `control` command, which cannot be used with the `--view=security` flag.
Before:
After:
> Fix scan command

- core/core/scan.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- core/pkg/resultshandling/results.go
- core/pkg/resultshandling/results_test.go
Sarif format is only available when scanning local files. This PR implements validation logic for sarif format, providing user-friendly error messages for non-supported scan types
> validate sarif format

- core/core/list.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/categorytable.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/configurationprinter/frameworkscan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils.go
- core/pkg/resultshandling/printer/v2/resourcetable.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
As stated in the issue, the table borders now can be colored by passing in a `gchalk` color function.
To accomplish this changes have been made to the forked upstream table library.
`kubescape list controls`
Before:
After:
Resolved #1380 
Resolved #1375
> feat: darken table borders

- cmd/scan/scan.go
- cmd/update/update.go
- core/pkg/resourcehandler/k8sresources.go
- core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
When running the `kubescape update` command with an old version, the output we currently get has an extra '%':
`Please refer to our installation docs in the following link: https://github.com/kubescape/kubescape/blob/master/docs/installation.md%`
This PR fixes that by adding a new line character, since the '%' sign comes from the bash / shell prompt
```
% ./kubescape update
Please refer to our installation docs in the following link: https://github.com/kubescape/kubescape/blob/master/docs/installation.md
%
```
> add new line

- cmd/root.go
Remove the default value of the `server` argument
Related PRs:
- https://github.com/kubescape/helm-charts/pull/283/files
> Remove ARMO server url

- .github/workflows/b-binary-build-and-e2e-tests.yaml
fixes missing image in kubescape release:
> force docker-build in absence of release label

- ADOPTERS.md
- GOVERNANCE.md
- MAINTAINERS.md
- README.md
- SECURITY-INSIGHTS.yml
- SECURITY.md
Implementing the following policy documents in the repo:
* Governance
* Security reports
* Security insights
* Change log
and updating the maintainers doc
> Adding project security and governance as per maintainer decision

- cmd/version/version.go
- cmd/version/version_test.go
Bug fix
___
This PR includes two main changes:
- A bug fix for the 'cmd version' command which was not showing any output when the build number was empty. Now, it will display 'unknown' when the build number is not available.
___
- `cmd/version/version.go`: Modified the 'RunE' function in the 'GetVersionCmd' command. Instead of directly using 'cautils.BuildNumber', a 'versionCheckRequest' object is created and used. This ensures that even if the 'BuildNumber' is empty, 'unknown' will be displayed as the version.
</details>
> Fix for Empty Build Number in cmd Version

- .github/workflows/00-pr-scanner.yaml
Added a check before running the binary-build job to ensure that the owner of the repository is kubescape.
Fixes: https://github.com/kubescape/kubescape/issues/1482
> Run binary-build job only for kubescape/kubscape

- core/pkg/score/score_test.go
Tests
___
This PR introduces a comprehensive test suite for the `core/pkg/score` package. The main changes include:
- Addition of new test cases to validate the functionality of the `NewScoreWrapper` function with various scenarios.
- Tests for the `Calculate` function to ensure it handles different report versions correctly.
- Use of the `assert` package for test assertions.
___
- `core/pkg/score/score_test.go`: Introduced multiple test functions including `TestNewScoreWrapper`, `TestNewScoreWrapperWithNilOPASessionObj`, `TestNewScoreWrapperWithNilAllResources`, `TestCalculateReturnsNilErrorWhenReportVersionIsEPostureReportV2`, `TestCalculateReturnsErrorWhenReportVersionIsEPostureReportV1`, and …
> Adding Test Suite for core/pkg/score

- core/cautils/datastructuresmethods.go
- core/cautils/datastructuresmethods_test.go
- core/cautils/versioncheck_test.go
Tests
___
This PR introduces the following changes:
- Adds unit tests for the `ruleWithKSOpaDependency` function in `core/cautils/datastructuresmethods_test.go`.
- Refactors the `ruleWithKSOpaDependency` function in `core/cautils/datastructuresmethods.go` to handle type assertion of the "armoOpa" attribute.
___
- `core/cautils/datastructuresmethods.go`: Refactored the `ruleWithKSOpaDependency` function to handle type assertion of the 'armoOpa' attribute.
- `core/cautils/datastructuresmethods_test.go`: Added unit tests for the `ruleWithKSOpaDependency` function, covering cases when attributes are nil, do not contain 'armoOpa' key, contain 'armoOpa' key with non-boolean value, and contain 'armoOpa' key with value 'true'.
</details>
> Adding Tests and Refactoring for ruleWithKSOpaDependency Function in cautils

- core/pkg/fixhandler/yamlhelper_test.go
Tests
___
This PR introduces a comprehensive test suite for the 'yamlhelper' package in the 'fixhandler' directory. The tests cover various scenarios and edge cases for the functions in the package. Here are the key changes:
- Addition of numerous test functions in the 'yamlhelper_test.go' file.
- Each function tests a specific function in the 'yamlhelper' package.
- The tests cover different scenarios including handling of empty strings, line and column matching, node encoding, content indentation, line removal, and more.
___
- `core/pkg/fixhandler/yamlhelper_test.go`: Added a comprehensive set of test functions to validate the behavior of the functions in the 'yamlhelper' package. Each test function corresponds to a function in the 'yamlhelper' …
> Adding Comprehensive Test Suite for yamlhelper Package

- core/core/list.go
- core/core/list_test.go
Bug fix
___
This PR addresses a bug that could cause an index out-of-range error when handling malformed policies. The changes include:
- A more robust handling of edge cases in the `generateControlRows` function to prevent potential errors.
- Addition of a new test case to verify the correct handling of policies with missing or extra '|' characters.
___
- `core/core/list.go`: The `generateControlRows` function has been updated to handle edge cases where the policy string is malformed. It now checks the length of the `idAndControlAndFrameworks` slice before attempting to access its elements, thus preventing an index out-of-range error.
- `core/core/list_test.go`: A new test case `TestGenerateControlRowsHandlesPoliciesWithEmptyStringOrNoPipesOrOnePipeMiss …
> Fix for Index Out of Range Error in Malformed Policies Handling

- core/pkg/fixhandler/yamlhelper.go
- core/pkg/fixhandler/yamlhelper_test.go
Bug fix
___
This PR focuses on improving the robustness of the `yamlhelper` package by handling edge cases that could lead to index out of range errors or other unexpected behaviors. It also adds several edge-case tests to ensure the correctness of these changes. The main changes include:
- Adding checks to prevent index out of range errors in various functions.
- Modifying some functions to handle edge cases such as negative indices or empty slices.
- Adding new test cases to `yamlhelper_test.go` to verify the correct handling of these edge cases.
___
- `core/pkg/fixhandler/yamlhelper.go`: Added checks to prevent index out of range errors in functions like `adjustContentLines`, `adjustFixedListLines`, `enocodeIntoYaml`, `indentContent`, `getNodeLine`, …
> Edge-case Handling and Test Enhancements in yamlhelper

- core/pkg/policyhandler/handlepullpolicies_test.go
- core/pkg/policyhandler/handlepullpoliciesutils_test.go
Tests
___
This PR introduces a comprehensive test suite for the `core/pkg/policyhandler` package. The main changes include:
- Mocking of various policy-related entities such as ExceptionsGetter, ControlsInputsGetter, and PolicyGetter.
- Addition of test cases for functions like `CollectPolicies`, `DownloadScanPolicies`, `GetExceptions`, `GetControlInputs`, etc.
- Enhancement of existing test cases in `handlepullpoliciesutils_test.go` to cover more scenarios.
___
- `core/pkg/policyhandler/handlepullpolicies_test.go`: This file has been significantly expanded with new test cases. Mock objects for ExceptionsGetter, ControlsInputsGetter, and PolicyGetter have been introduced. New test cases have been added for `CollectPolicies`, `DownloadScanPolicies`, …
> Adding Test Suite for core/pkg/policyhandler

- core/core/initutils.go
- core/core/initutils_test.go
Tests
___
This PR includes the following changes:
- Added comprehensive unit tests for the functions in the `core/core/initutils.go` file.
- Fixed a potential bug in the `setSubmitBehavior` function in `core/core/initutils.go` by replacing `getter.GetKSCloudAPIConnector().GetCloudReportURL()` with `tenantConfig.GetCloudReportURL()`.
___
- `core/core/initutils.go`: Replaced `getter.GetKSCloudAPIConnector().GetCloudReportURL()` with `tenantConfig.GetCloudReportURL()` in the `setSubmitBehavior` function to fix a potential bug.
- `core/core/initutils_test.go`: Added comprehensive unit tests for the functions in the `core/core/initutils.go` file. This includes tests for `getExceptionsGetter`, `policyIdentifierIdentities`, `getUIPrinter`, `GetSensorHandler`, …
> Adding tests for core/core/initutils and fixing potential bug

- cmd/shared/image_scan_test.go
Tests
___
This PR introduces unit tests for the `cmd/shared` package. The tests are focused on validating the `ScanInfo` struct, particularly the `FailThresholdSeverity` field. Different scenarios are tested including valid and invalid severity levels.
___
- `cmd/shared/image_scan_test.go`: Added a new test file for the `shared` package. The file contains a test function `TestValidateImageScanInfo` which tests the validation of a `ScanInfo` struct with different `FailThresholdSeverity` values.
</details>
> Adding Unit Tests for cmd/shared Package

- cmd/update/update.go
- core/cautils/versioncheck.go
- core/cautils/versioncheck_test.go
Enhancement
___
This pull request primarily focuses on enhancing the 'update' command in the 'update.go' file and adding tests for the version check functionality in the 'versioncheck_test.go' file. The main changes include:
- In 'update.go', the 'update' command now checks for the latest version of Kubescape and provides more informative messages to the user based on different scenarios.
- In 'versioncheck.go', the 'CheckLatestVersion' function has been updated to assign the latest version to 'LatestReleaseVersion' and not to a new variable.
- New tests have been added in 'versioncheck_test.go' to test the 'CheckLatestVersion' and 'getLatestVersion' functions.
___
- `cmd/update/update.go`: Enhanced the 'update' command to check for the latest version …
> Enhancement of 'update' command and addition of tests for version check

- core/pkg/policyhandler/cache.go
- core/pkg/policyhandler/cache_test.go
Bug fix
___
This PR introduces several enhancements and bug fixes to the `TimedCache` in the `core/pkg/policyhandler/cache.go` file. The main changes include:
- Replacing the `expiration` field's type from `int64` to `time.Time` to simplify expiration checks.
- Adding a `stopChan` field and a `Stop` method to properly stop the `invalidateTask` goroutine, preventing direct value changes.
- Using a `Ticker` in `invalidateTask` for periodic expiration checks.
- Implementing a leak prevention mechanism: the `invalidateTask()` loop now checks the TTL value before continuing. If the TTL is zero, the goroutine exits gracefully, preventing a potential memory leak.
- Adding a comprehensive test suite for the `TimedCache` in the `core/pkg/policyhandler/cache_test.go` file.
___
<details> …
> Enhancement of TimedCache with Bug Fixes and Test Suite

- cmd/completion/completion_test.go
- cmd/config/config_test.go
- cmd/config/delete_test.go
- cmd/config/set.go
- cmd/config/set_test.go
- cmd/config/view_test.go
- core/mocks/cmd_mocks.go
Tests
___
This PR introduces a comprehensive test suite for the `cmd` package, specifically targeting the `completion` and `config` sub-packages. The main changes include:
- Addition of new test cases for the `completion` package to validate the generation of autocompletion scripts for valid shell types.
- Addition of new test cases for the `config` package, including tests for the `delete`, `set`, and `view` subcommands.
- Enhancement of the `stringKeysToSlice` function in the `config` package to return the final string slice in sorted order of keys.
___
- `cmd/completion/completion_test.go`: Added new tests for the `completion` package, checking the properties of the generated autocompletion command.
- `cmd/config/config_test.go`: Introduced new tests …
> Enhancement of Test Suite for cmd Packages

- core/core/download_test.go
- core/core/fix_test.go
- core/core/list_test.go
- core/core/scan_test.go
Tests
___
This PR introduces a comprehensive test suite for the `core/core` package in the Go language. The main changes include:
- Addition of unit tests for the `download.go`, `fix.go`, `list.go`, and `scan.go` files in the `core/core` package.
- The tests cover various scenarios and edge cases, ensuring the robustness of the code.
- The use of the `assert` package for test assertions.
___
- `core/core/download_test.go`: Added numerous test cases for functions in the `download.go` file. These tests cover functions like `DownloadSupportCommands`, `DownloadArtifact`, `SetPathAndFilename`, `DownloadArtifacts`, `DownloadConfigInputs`, `DownloadExceptions`, `DownloadAttackTracks`, `DownloadFramework`, and `DownloadControl`.
- `core/core/fix_test.go`: …
> Adding Test Suite for the core/core package

- cmd/operator/configscan_test.go
- cmd/operator/operator_test.go
- cmd/operator/scan_test.go
- cmd/operator/vulnerabilitiesscan_test.go
- cmd/patch/patch.go
- cmd/patch/patch_test.go
- cmd/scan/control_test.go
- cmd/scan/framework_test.go
- cmd/scan/image.go
- cmd/scan/image_test.go
- cmd/scan/scan_test.go
- cmd/scan/workload.go
- cmd/scan/workload_test.go
Tests
___
This PR introduces a comprehensive test suite for the 'cmd' packages in the Go codebase. It also includes a fix for a potential crash in the 'image' subcommand within the 'scan' package. The main changes are:
- Addition of new test cases for the 'operator', 'patch', and 'scan' packages.
- Modification of the 'image' subcommand in the 'scan' package to prevent potential crashes.
- Minor adjustments in the 'patch' package to improve code readability.
___
- `cmd/operator/configscan_test.go`: Added a new test suite for the 'configscan' subpackage in the 'operator' package.
- `cmd/operator/operator_test.go`: Introduced a new test suite for the 'operator' package.
- `cmd/operator/scan_test.go`: Added a new test suite for the 'scan' subpackage in the …
> Add Test Suite for cmd Packages and Fix Potential Crash in Image Subcommand

- pkg/imagescan/imagescan.go
- pkg/imagescan/imagescan_test.go
Bug fix
___
This PR includes two main changes:
- A bugfix in the 'pkg/imagescan' package, specifically in the 'ExceedsSeverityThreshold' function. A nil pointer error was fixed by adding a check for 'nil' before using 'scanResults.MetadataProvider'.
- Addition of tests in 'pkg/imagescan/imagescan_test.go'. The tests cover various functions in the 'imagescan' package including 'ExceedsSeverityThreshold', 'RegistryCredentials.IsEmpty', 'ParseSeverity', and 'validateDBLoad'.
___
- `pkg/imagescan/imagescan.go`: Added a nil check for 'scanResults.MetadataProvider' in the 'ExceedsSeverityThreshold' function to prevent a nil pointer error.
- `pkg/imagescan/imagescan_test.go`: Added a variety of tests for the 'imagescan' package functions. The tests cover …
> Bugfix and Tests for Image Scan Package

- core/pkg/fixhandler/fixhandler.go
- core/pkg/fixhandler/fixhandler_test.go
Bug fix
___
This PR addresses a minor bug in the `sanitizeYaml` and `revertSanitizeYaml` functions and adds tests for the `core/pkg/fixhandler` package. The changes include:
- A bug fix in the `sanitizeYaml` and `revertSanitizeYaml` functions to handle cases where the input string length is less than 3.
- Addition of numerous tests for various functions in the `core/pkg/fixhandler` package.
___
- `core/pkg/fixhandler/fixhandler.go`: Added condition to handle cases where the input string length is less than 3 in `sanitizeYaml` and `revertSanitizeYaml` functions.
- `core/pkg/fixhandler/fixhandler_test.go`: Added numerous tests for various functions in the `core/pkg/fixhandler` package, including `TestJoinStrings`, `TestGetFileString`, …
> Bug Fix and Test Addition for sanitizeYaml and revertSanitizeYaml Functions

- cmd/patch/patch_test.go
Title: Add Test Case for Non-Existent Image in GetPatchCmd
Resolves issue #1530 
**Description:**
This pull request introduces a new test case TestGetPatchCmdWithNonExistentImage in the patch_test.go file. The purpose of this test case is to verify the behavior of the GetPatchCmd function when it's run with a non-existent image argument.
In this test case, we:
- Create a mock Kubescape interface
- Call the GetPatchCmd function with the mock interface
- Run the command with a non-existent image argument
- Check that there is an error and the error message is "image tag is required"
This test case enhances the test coverage of the GetPatchCmd function and ensures that it correctly handles non-existent image arguments.
> Update patch_test.go (Add Test Case for Non-Existent Image in GetPatchCmd)

- cmd/completion/completion_test.go
**Issue:** Resolves issue #1519 
Update completion_test.go
Pull Request Description:
**Changes Made**
Added new test cases for different shell completions in the completion package to enhance test coverage.
**New Test Cases**
- TestGetCompletionCmd_RunBashCompletionNotExpectedOutputs: Tests that the output for Bash completion does not match the specified unexpected outputs.
- TestGetCompletionCmd_RunZshCompletionNotExpectedOutputs: Tests that the output for Zsh completion does not match the specified unexpected outputs.
- TestGetCompletionCmd_RunFishCompletionNotExpectedOutputs: Tests that the output for Fish completion does not match the specified unexpected outputs.
- TestGetCompletionCmd_RunPowerShellCompletionNotExpectedOutputs: Tests that the output for PowerShell completion does not …
> Added new test cases for different shell completions in the completion package to enhance test coverage.

- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/tablewriter_test.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils_test.go
Tests
___
___
- `core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/tablewriter_test.go`: Added tests for the `PrintImageScanningTable` and `NewTableWriter` functions. The tests for `PrintImageScanningTable` check if CVEs are sorted by severity and if fixed CVEs show versions.
- `core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/imageprinter/utils_test.go`: Added a new test for the `renderTable` function, which checks if CVEs are sorted by severity and if fixed CVEs show versions.
</details>
> Added new tests in the imagewriter package

- core/pkg/resultshandling/printer/v2/prettyprinter/clusterscan_test.go
- core/pkg/resultshandling/printer/v2/prettyprinter/frameworkscan_test.go
- core/pkg/resultshandling/printer/v2/prettyprinter/imagescan_test.go
Tests
___
This PR focuses on enhancing the test coverage for the `prettyprinter` package. The following changes have been made:
- Added tests for the `clusterscan_test.go` file. The tests cover the `TestClusterScan_getNextSteps`, `TestNewClusterPrinter`, `TestPrintNextSteps`, and `TestGetWorkloadScanCommand` functions.
- Added tests for the `frameworkscan_test.go` file. The tests cover the `TestNewSummaryPrinter` and `TestGetVerboseMode` functions.
- Added tests for the `imagescan_test.go` file. The tests cover the `TestNewImagePrinter` and `TestPrintNextSteps_ImageScan` functions.
___
- `core/pkg/resultshandling/printer/v2/prettyprinter/clusterscan_test.go`: Added tests for the `TestClusterScan_getNextSteps`, `TestNewClusterPrinter`, …
> Addition of Tests for the PrettyPrinter Package

- core/cautils/versioncheck_test.go
- core/pkg/resultshandling/printer/v2/junit_test.go
- core/pkg/resultshandling/printer/v2/pdf_test.go
Tests
___
This PR introduces new tests for the junit printer, version check and PDF printer functionalities. The main changes include:
- Addition of tests for the `listTestsSuite`, `testsSuites`, `properties`, and `SetWriter` functions in the junit printer.
- Addition of tests for `getTriggerSource` function in version check.
- Addition of tests for `SetWriter` function in PDF printer.
- The tests cover various scenarios and edge cases, ensuring the robustness of the code.
___
- `core/cautils/versioncheck_test.go`: A new test has been added for the `getTriggerSource` function in the version check. The test verifies the function's behavior when running in a GitHub Actions pipeline and when the first argument is "ksserver".
- …
> Addition of new tests for junit printer, version check and PDF printer

- core/pkg/resultshandling/printer/v2/prettyprinter/utils.go
Updated the `getSortPackageScores` function to fix the crash in the scan command.
Fixes: https://github.com/kubescape/kubescape/issues/1553
> Fixed crash when running the scan command

- examples/output_mocks/html-format.html
> Remove control 0086

- .github/workflows/d-publish-image.yaml
- build/kubescape-cli.Dockerfile
Bug fix
___
This PR addresses issues with the Docker build process for the Kubescape-CLI. The changes include:
- Renaming the kubescape binaries for amd64 and arm64 architectures.
- Changing the chmod command to apply to the renamed binaries.
- Modifying the Docker build and push command to work with the renamed binaries and support multiple platforms.
- Updating the Dockerfile to copy the renamed binary into the image and remove unused arguments.
___
- `.github/workflows/d-publish-image.yaml`: The kubescape binaries for amd64 and arm64 are renamed. The chmod command is updated to apply to the renamed binaries. The Docker build and push command is modified to work with the renamed binaries and support multiple platforms.
- …
> Fix Docker Build for Kubescape-CLI

- docs/getting-started.md
Just fixed a markdown syntax error
> Fix markdown syntax error

- core/pkg/resultshandling/printer/v2/pdf.go
- core/pkg/resultshandling/printer/v2/prettyprinter.go
- core/pkg/resultshandling/printer/v2/prettyprinter/tableprinter/utils/utils.go
Fixed the `%!)(MISSING)` from the results 
Before:
After:
> Remove "%" from the print

- core/pkg/policyhandler/handlepullpolicies.go
- core/pkg/policyhandler/handlepullpoliciesutils.go
- core/pkg/policyhandler/handlepullpoliciesutils_test.go
Updating error message in case of unknown framework.
Before:
```
% kubescape scan framework cis
✅  Initialized scanner
❌  http-error: '400 Bad Request', reason: 'framework 'cis' not found`
```
After:
```
% kubescape scan framework cis
✅  Initialized scanner
❌  framework 'cis' not found, run `kubescape list frameworks` for available frameworks
```
> Handle unknown fw

- core/cautils/datastructures.go
- core/cautils/fileutils.go
- core/cautils/fileutils_test.go
- core/cautils/helmchart.go
- core/cautils/helmchart_test.go
- core/cautils/mappingnode.go
- core/cautils/parseFile.go
- core/cautils/parseFile_test.go
- core/pkg/resourcehandler/filesloader.go
- core/pkg/resultshandling/printer/v2/resourcetable.go
- core/pkg/resultshandling/printer/v2/resourcetable_test.go
- core/pkg/resultshandling/printer/v2/sarifprinter.go
- examples/helm_chart_mapping_node/Chart.yaml
- examples/helm_chart_mapping_node/templates/_helpers.tpl
- examples/helm_chart_mapping_node/templates/clusterrole.yaml
- examples/helm_chart_mapping_node/templates/clusterrolebinding.yaml
- examples/helm_chart_mapping_node/templates/configmap.yaml
- examples/helm_chart_mapping_node/templates/cronjob.yaml
- examples/helm_chart_mapping_node/templates/role.yaml
- examples/helm_chart_mapping_node/templates/rolebinding.yaml
- examples/helm_chart_mapping_node/templates/serviceaccount.yaml
- examples/helm_chart_mapping_node/values.yaml
Mapping struct is defined in. 'mappingnode.go'. Three mapping objects are used, the connection among them is that one MappingNode represents one line in one template, MappingNodes represents one template, FileMapping represents one file, and one file can contain many template.
GetMapping function in GetWorkLoads function is to call yqlib package to form the FileMapping, which is the most important part.
Adding one more output FileMapping for GetWorkLoads function and change all the related functions which call it.
After that, I connect the Filemappingwith sarif Printer. After connecting, I can use the mapping to generate correct location and fixed object for helm chart.
Kubescape can scan helm chart files, however, Helm does not give information about which output line is coming from …
> feat: Add the debugging ability for scanning Helm chart

- cmd/scan/framework.go
remove some redundant code
1. there are two lines of "scanInfo.FrameworkScan = true" in the same level, so remove one.
2. when "len(args) > 1" len(args[1:]) must be > 0, so no need to check, remove it.
- [x ] My code follows the style guidelines of this project
- [x ] New and existing unit tests pass locally with my changes
> fix(cmd/scan/framework.go): remove redundant code

- core/cautils/fileutils.go
- core/cautils/helmchart.go
- core/cautils/parseFile.go
- core/pkg/resourcehandler/filesloader.go
When executing yqlib, if there is an error, it will return, which causes the crash of Kubescape scanning.
To fix it, instead of generating an error and return, I print a warning log to tell users which files are failing to execute yqlib. Therefore, it will only generate a warning for the files, and scanning will not be stopped.
In this case, in the sarif printer, since the files don't have the file mapping, it will return the default location. The worst case will be all the files fail to execute yqlib, but this is really rare.
`./kubescape scan framework allcontrols ./demo-bitnami-charts -f sarif -o test1.sarif`
* Resolved #1625
> Fix bug for no matches of yalib in one file mapping

- .github/workflows/a-pr-scanner.yaml
- .github/workflows/b-binary-build-and-e2e-tests.yaml
https://github.com/golangci/golangci-lint-action/issues/703
> speedup golangci-lint-action by skipping caches

- core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
When an error is returned from `SubmitReport`, Kubescape calls `getReportUrl()` (for logging purposes) which causes a panic since it is empty.
```
{"level":"debug","ts":"2024-03-17T04:35:44Z","msg":"sending report","url":"https://report.armo.cloud/k8s/v2/postureReport?clusterName=kind-systets-1f6ac241-7723-4fff-8b5d-2dacdca93e26&contextName=kind-systets-1f6ac241-7723-4fff-8b5d-2dacdca93e26&customerGUID=69bcb204-5b2d-446a-896f-ff68a2312be9&reportGUID=8a8323e8-18aa-416a-bfd3-3a0fa96506b4","account":"69bcb204-5b2d-446a-896f-ff68a2312be9","accessKey length":0,"reportNumber":0}
{"level":"debug","ts":"2024-03-17T04:36:45Z","msg":"updating cached config","configObj":{"clusterName":"kind-systets-1f6ac241-7723-4fff-8b5d-2dacdca93e26","cloudReportURL":"https://report.armo.cloud/","cloudAPIURL":"http …
```
> Fix panic when error is returned from SubmitReport

- .github/workflows/02-release.yaml
- .github/workflows/04-publish-krew-plugin.yaml
- .github/workflows/a-pr-scanner.yaml
- .github/workflows/b-binary-build-and-e2e-tests.yaml
- .github/workflows/d-publish-image.yaml
- .github/workflows/scorecard.yml
[Scorecard analysis](https://github.com/kubescape/node-agent/actions/runs/8413161701/job/23034977535)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> bump actions/checkout to v4

- core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
A continuation of https://github.com/kubescape/kubescape/pull/1640
```
goroutine 1 [running]:
github.com/google/uuid.MustParse({0x0, 0x0})
/home/runner/go/pkg/mod/github.com/google/uuid@v1.6.0/uuid.go:169 +0x99
github.com/kubescape/backend/pkg/client/v1.GetPostureReportUrl({0xc001896c00?, 0x42824f1?}, {0x0, 0x0}, {0xc0011e6380, 0x31}, {0xc0014bb6b0, 0x24})
/home/runner/go/pkg/mod/github.com/kubescape/backend@v0.0.19/pkg/client/v1/reporter.go:69 +0x175
github.com/kubescape/kubescape/v3/core/pkg/resultshandling/reporter/v2.(*ReportEventReceiver).getReportUrl(0xc000e05570)
/home/runner/work/kubescape/kubescape/core/pkg/resultshandling/reporter/v2/reporteventreceiver.go:121 +0xb1
github.com/kubescape/kubescape/v3/core/pkg/resultshandling/reporter/v2.(*ReportEventReceiver).Submit(0xc000e05570, …
```
> fix panic when submitting report

- core/pkg/resultshandling/printer/v2/controltable.go
- core/pkg/resultshandling/printer/v2/controltable_test.go
- core/pkg/resultshandling/printer/v2/pdf.go
This PR adds a new column in the PDF output to reference each control that has been executed as control ID.
The PDF report is useful, especially for assessment overviews.
As of now a reference to each control, independently of the framework, is missing and only a description.
The description of the control is not enough to reference the documentation of the control, remediation.
Furthermore, this PR increments the control description volume width to 73 characters, from 53.
```shell
kubescape scan -v --format pdf --output test-report.pdf
```
#1661
> chore(core/pkg/resultshandling): add control id to pdf output

- core/cautils/remotegitutils.go
- core/cautils/remotegitutils_test.go
- core/cautils/scaninfo.go
- core/cautils/scaninfo_test.go
- core/pkg/resourcehandler/filesloader.go
- core/pkg/resultshandling/printer/v2/prettyprinter/reposcan.go
- core/pkg/resultshandling/printer/v2/prettyprinter/reposcan_test.go
- core/pkg/resultshandling/results.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
We encountered several issues with repository scanning:
1. Scanning a remote repository resulted in the scanning process occurring on the remote repository, but the scanning metadata was stored in the current directory from which we initiated the scan.
2. There was confusion between local scanning and repository scanning, leading to numerous unpredictable behaviors.
3. The output file paths were incorrect.
> Fix scanning repo

- core/pkg/resourcehandler/k8sresources.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
This PR fixes the panic we get when scanning unsupported clouds.
I scanned a cluster running on DigitalOcean and I got the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6a7c2]
goroutine 10 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.24.0/trace/span.go:405 +0x25
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000ff8300, {0x0, 0x0, 0xbad95c8cf62385b4?})
/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.24.0/trace/span.go:443 +0xa3b …
```
> Fix scanning unsupported clouds

- cmd/scan/scan.go
- core/cautils/scaninfo.go
- core/core/scan.go
- core/pkg/opaprocessor/processorhandler.go
- core/pkg/opaprocessor/processorhandler_test.go
- httphandler/handlerequests/v1/requestshandlerutils.go
This is a long overdue feature: implementing the option to send `print()` statements in rego/OPA to the Kubescape log output.
Note: to use it you need both `-l debug` and `--enable-rego-prints` flags in the CLI and `KS_REGO_PRINT=true` and debug log level in the microservice
> Implementing capability to print out the "print" statements of the rego

- cmd/scan/scan.go
- core/cautils/datastructures.go
- core/cautils/scaninfo.go
- core/pkg/resultshandling/reporter/v2/reporteventreceiverutils.go
- go.mod
- go.sum
- httphandler/go.mod
- httphandler/go.sum
A new field in the posture report to indicate whether the scan was triggered by CLI (or http handler).
We set the `TriggeredByCLI` to `true` only when ScanInfo is initialized in the command package, in all other places it will be false by default.
* https://github.com/kubescape/opa-utils/pull/155
> add trigger by indication in posture report

- cmd/download/download.go
- cmd/list/list.go
- cmd/scan/framework.go
- core/cautils/fileutils.go
- core/core/scan.go
- core/pkg/opaprocessor/processorhandler.go
- core/pkg/opaprocessor/utils.go
- go.mod
The experimental functions in `golang.org/x/exp/slices` are now part of the Go standard library as of Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
I have submitted PRs to the following downstream repositories:
1. https://github.com/kubescape/k8s-interface/pull/117
2. https://github.com/kubescape/opa-utils/pull/156
3. https://github.com/kubescape/storage/pull/186
Please review them as well. Thank you :blush:
> Replace `golang.org/x/exp/slices` with `slices` from stdlib

- go.mod
- httphandler/handlerequests/v1/datastructuremethods.go
- Update opa-utils from v0.0.273 to v0.0.275 to add Exception in --data payload
- Added loadexception function which runs when scanRequest or payload contains an Exception  
Here is the command to test weather the Exception Payload is load or not 
```
curl --header "Content-Type: application/json"   --request POST   --data '{"Exceptions": [{"name":"exclude-allowed-hostPath-control","policyType":"postureExceptionPolicy","actions":["alertOnly"],"resources":[{"designatorType":"Attributes","attributes":{"kind":".*"}}],"posturePolicies":[{"controlName":"HostPath mount"}]}]}'   http://127.0.0.1:8080/v1/scan
```
I used this Exception example [exclude-allowed-hostPath-control](https://github.com/kubescape/kubescape/blob/master/examples/exceptions/exclude-allowed-hostPath-control.json)
> Here are …
> added support for exception rules in Scan API ( As a HTTP request)

- cmd/config/delete.go
- cmd/download/download.go
- cmd/fix/fix.go
- cmd/list/list.go
- cmd/patch/patch.go
- cmd/root.go
- cmd/scan/control.go
- cmd/scan/framework.go
- cmd/scan/image.go
- cmd/scan/scan.go
- cmd/scan/workload.go
- cmd/version/version.go
- cmd/version/version_test.go
- core/core/cachedconfig.go
- core/core/download.go
- core/core/fix.go
- core/core/image_scan.go
- core/core/kscore.go
- core/core/kscore_test.go
- core/core/list.go
- core/core/patch.go
- core/core/scan.go
- core/meta/ksinterface.go
- core/mocks/cmd_mocks.go
- downloader/main.go
- httphandler/handlerequests/v1/requestshandlerutils.go
- main.go
This PR refactors the program to centralize context management by using a single context propagated throughout the application. The context is created in the `main()` function, where it listens for interrupt signals (os.Interrupt, syscall.SIGTERM), and is then passed to the rest of the program.
- Created the context in `main()` to handle interrupt signals.
- Replaced redundant context creation in multiple functions with the propagated context.
- Improved graceful shutdown handling by utilizing a single context.
- Ensured the program consistently reacts to shutdown signals across all components.
- Improved readability and maintainability by eliminating context duplication.
- Ensured that all components share the same context, allowing for easier management of timeouts, cancellations, and …
> Refactor: propagate context from main to avoid redundant context creation

- core/core/fix_test.go
Fixed an issue in TestUserConfirmed where the standard input wasn't properly restored after test execution. The previous implementation attempted to restore os.Stdin to itself rather than to the original value.
This change saves the original stdin before modifying it and properly restores it in the defer function, ensuring that test cases don't affect each other and that the standard input is correctly reset after tests complete.
> fix: Fix stdin restoration in TestUserConfirmed

- main.go
This PR fixes an issue where the deferred `stop()` (from `signal.NotifyContext`) would not be executed if `logger.L().Fatal(...)` is called due to a command failure. Since `Fatal` internally invokes `os.Exit(1)`, any deferred functions — including `stop()` — are skipped.
To address this, an explicit call to `stop()` is added before `Fatal` to ensure that the context is properly cancelled. This guarantees that any goroutines waiting on `ctx.Done()` can proceed with cleanup or shutdown logic.
- Added `stop()` before `logger.L().Fatal(...)` in `main`.
> Ensure context cancellation on command execution failure

- core/pkg/resourcehandler/k8sresources.go
- core/pkg/resourcehandler/k8sresources_test.go
This pull request updates the `isMasterNodeTaints` function in `k8sresources.go` to improve its logic for identifying master nodes based on taints. Corresponding test cases in `k8sresources_test.go` have been updated and extended to ensure comprehensive coverage of the new logic.
* Enhanced the logic to include a check for the taint key `node-role.kubernetes.io/control-plane` with a value of `"true"`, in addition to the existing check for `NoSchedule` taints with an empty value.
* Refactored test node JSON variable names to improve clarity (`noTaintNode` → `noTaintNodeJson`, `taintNode` → `taintNodeJson`). [[1]](diffhunk://#diff-ea902dd68c6568d5532e2e53a60e140aba61e55fc8146fe403655bb9bed77d43L17-R17) [[2]](diffhunk://#diff-ea902dd68c6568d5532e2e53a60e140aba61e55fc8146fe403655bb9bed77d43L27 …
> fix: control-plane node taints check

- core/pkg/resultshandling/printer/v2/resourcetable.go
- core/pkg/resultshandling/printer/v2/resourcetable_test.go
As requested in the [issue](https://github.com/kubescape/kubescape/issues/1817), currently we only show the container indexes in AssistedRemediation not the container names during kubescape scan control
Implemented a step to add container name along with container indexes in the Assisted remediation
**Existing flow**: 
- Controls are applied for each resource
- For every resource , if there is any assisted remediation against a control, we get it from results
**Changes:**
- Iterate over the assisted remediation path, Check if the path contains container indexes using regex
- Get the index of container
- Get the container name using workloadinterface 
1. Run scan control command
kubescape scan control C-0013 -v
Container name is present in Assisted remediation Path 
* Resolved #1817 
put …
> Issue 1817 fix: Show container name in Assisted remediation

- cmd/patch/patch.go
- cmd/scan/image.go
- cmd/scan/scan.go
- core/cautils/scaninfo.go
- core/core/image_scan.go
- core/core/patch.go
- core/core/scan.go
- core/meta/datastructures/v1/image_scan.go
- pkg/imagescan/imagescan.go
- pkg/imagescan/imagescan_test.go
hey! added the default matchers option for image scanning as requested in #1838. now you can choose between stock matchers and CPE matchers when scanning images.
what's new:
- added --use-default-matchers flag to scan/image/patch commands
- true = stock matchers (default behavior)
- false = CPE matchers (more precise)
usage:
kubescape scan image nginx:latest --use-default-matchers=false
kubescape scan --scan-images --use-default-matchers=false
everything's backward compatible - existing code works exactly the same. just added the new option for folks who want more control over their vulnerability detection.
fixes #1838
> feat: add default matchers option to image scanning

- cmd/vap/vap.go
As stated in the https://github.com/kubescape/kubescape/issues/1800 , kubescape vap create-policy-binding fails when --parameter-reference flag is passed 
Starting with Kubernetes v1.29+, the field spec.paramRef.parameterNotFoundAction has become mandatory when defining a paramRef in a ValidatingAdmissionPolicyBinding.
To comply with new requirement , fixed the issue by setting 
policyBinding.spec.paramRef.parameterNotFoundAction = Deny
Create policy binding with parameter reference flag
e.g kubescape vap create-policy-binding --name <policy-name> --policy kubescape-c-0046-deny-resources-with-insecure-capabilities --namespace default --parameter-reference basic-control-configuration | kubectl apply -f -
This command now runs successfully, which otherwise fails as  parameterNotFoundAction …
> Fixed issue #1800 : Added parameterNotFoundAction in spec.paramRef while creating policy binding 

- install.sh
The installation script runs a scan at the end.
It follows the same script ending as the PowerShell version; it prints the version and usage:
https://github.com/kubescape/kubescape/blob/7ebf078d0c986566e4795b15a829eb789df68436/install.ps1#L37-L39
Resolves #1874
> fix: Don't run scan in installation script

- .github/workflows/e-post-release.yaml
Post release job is not taking properly the tag passed via GITHUB_REF env var.
Can be seen here: https://github.com/kubescape/kubescape/actions/runs/17795795208/job/50587625231#step:4:6
According to the logic of the action, passing a tag requires a `refs/tags` prefix 
https://github.com/rajatjindal/krew-release-bot/blob/e2d6f27e6d51bdc2a0a92c1347810134c903c273/pkg/cicd/github/actions.go#L50
> fix: post release action does not take tag from GITHUB_REF env var
